// This file is autogenerated by a script

export interface GarrysModAdapter {
  stats: GarrysModStats;
  achievements: GarrysModAchievements;
}

interface GarrysModStats {
  /**
   * ### Startups
   * - default value: `0`
   */
  GMA_X_STARTUPS_STAT: number;

  /**
   * ### Minutes Played
   * - default value: `0`
   */
  GMA_X_MINUTES_STAT: number;

  /**
   * ### Maps Played
   * - default value: `0`
   */
  GMA_X_MAPS_STAT: number;

  /**
   * ### Baddies Killed
   * - default value: `0`
   */
  GMA_BADDIES_STAT: number;

  /**
   * ### Bystanders Killed
   * - default value: `0`
   */
  GMA_BYSTANDER_STAT: number;

  /**
   * ### Goodies Killed
   * - default value: `0`
   */
  GMA_GOODIES_STAT: number;

  /**
   * ### Balls Eaten
   * - default value: `0`
   */
  GMA_BALLEATER_STAT: number;

  /**
   * ### Props Spawned
   * - default value: `0`
   */
  GMA_PROPSPAWNER_STAT: number;

  /**
   * ### Balloons Spawned
   * - default value: `0`
   */
  GMA_BALLOONPOPPER_STAT: number;

  /**
   * ### Entities Removed
   * - default value: `0`
   */
  GMA_REMOVER_STAT: number;

  /**
   * ### Spawnmenus Opened
   * - default value: `0`
   */
  GMA_SPAWNMENUER_STAT: number;

  /**
   * ### Lua Errors Seen
   * - default value: `0`
   */
  GMA_BADCODER_STAT: number;

  /**
   * ### NPCs Spawned
   * - default value: `0`
   */
  GMA_NPCSPAWNER_STAT: number;

  /**
   * ### Ragdolls Spawned
   * - default value: `0`
   */
  GMA_RAGDOLLSPAWNER_STAT: number;

  /**
   * ### Thumbs Earned
   * - default value: `0`
   */
  NUM_WORKSHOP_THUMBS: number;

  /**
   * ### Most Thumbs
   * - default value: `0`
   */
  MOST_WORKSHOP_THUMBS: number;
}

interface GarrysModAchievements {
  /**
   * ### Play Singleplayer
   * Play singleplayer at least once
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_PLAY_SINGLEPLAYER: boolean;

  /**
   * ### Play Multiplayer
   * Play multiplayer at least once
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_PLAY_MULTIPLAYER: boolean;

  /**
   * ### Startup Millenium
   * Start Garry's Mod 1000 times
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_X_STARTUPS: boolean;

  /**
   * ### Secret Phrase
   * Say the secret phrase
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_SAY_1: boolean;

  /**
   * ### Addict
   * You have wasted a year of your life playing GMod!
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_X_MINUTES: boolean;

  /**
   * ### Map Loader
   * Play 20 different maps
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_X_MAPS: boolean;

  /**
   * ### Play Around
   * Play a gamemode that isn't sandbox
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_NOT_SANDBOX: boolean;

  /**
   * ### War Zone
   * Killed 1000 Baddies
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_BADDIES: boolean;

  /**
   * ### Friendly
   * Play with 10 friends
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_FRIENDS: boolean;

  /**
   * ### Yes, I am the real garry!
   * Play on the same server as garry
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_PLAYWITH_GARRY: boolean;

  /**
   * ### Marathon
   * Play on the same server & map for 8 hours
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_MARATHON: boolean;

  /**
   * ### Half Marathon
   * Play on the same server & map for 4 hours
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_HALFMARATHON: boolean;

  /**
   * ### One Day
   * 24 hours of your life wasted
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_DAY: boolean;

  /**
   * ### One Week
   * One whole week of your life wasted
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_WEEK: boolean;

  /**
   * ### One Month
   * One whole month of your life wasted
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_MONTH: boolean;

  /**
   * ### Innocent Bystander
   * Kill 1000 innocent animals
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_BYSTANDER: boolean;

  /**
   * ### Ball Eater
   * Eat 200 balls
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_BALLEATER: boolean;

  /**
   * ### Creator
   * Spawn 5000 props
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_PROPSPAWNER: boolean;

  /**
   * ### Popper
   * Burst 1000 balloons
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_BALLOONPOPPER: boolean;

  /**
   * ### Destroyer
   * Remove 5000 things
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_REMOVER: boolean;

  /**
   * ### Menu User
   * Open the spawnmenu 100,000 times
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_SPAWNMENUER: boolean;

  /**
   * ### Bad Coder
   * Experience 500 Lua programming errors
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_BADCODER: boolean;

  /**
   * ### Procreator
   * Spawn 1000 NPCs
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_NPCSPAWNER: boolean;

  /**
   * ### Dollhouse
   * Spawn 2000 ragdolls
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_RAGDOLLSPAWNER: boolean;

  /**
   * ### Bad Friend
   * Kill 1000 friendly NPCs
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_GOODIES: boolean;

  /**
   * ### 10 Thumbs
   * Your Workshop uploads got 10 thumbs
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_SMALLTHUMB: boolean;

  /**
   * ### 100 Thumbs
   * Your workshop uploads got 100 thumbs
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_MEDIUMTHUMB: boolean;

  /**
   * ### 1000 Thumbs
   * Your Workshop uploads got 1000 thumbs
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_HUGETHUMB: boolean;

  /**
   * ### Mega Upload
   * Get 1000 thumbs on a single upload (then go to jail)
   * - default value: `false`
   * - hidden: `false`
   */
  GMA_MEGAUPLOAD: boolean;
}
