export { CSGOAdapter } from './730_CSGO/CSGOAdapter';
export { TF2Adapter } from './440_TF2/TF2Adapter';
export { PortalAdapter } from './400_Portal/PortalAdapter';
export { Portal2Adapter } from './620_Portal2/Portal2Adapter';
export { RustAdapter } from './252490_Rust/RustAdapter';
export { PUBGAdapter } from './578080_PUBG/PUBGAdapter';
export { GTAVAdapter } from './271590_GTAV/GTAVAdapter';
export { RocketLeagueAdapter } from './252950_RocketLeague/RocketLeagueAdapter';
export { WarframeAdapter } from './230410_Warframe/WarframeAdapter';
