// This file is autogenerated by a script

export interface PUBGAdapter {
  stats: PUBGStats;
  achievements: PUBGAchievements;
}

interface PUBGStats {
  /**
   * ### ACHIEVE000_ACHIEVE000
   * - default value: `0`
   */
  ACHIEVE000_ACHIEVE000: number;

  /**
   * ### ACHIEVE001_ACHIEVE001
   * - default value: `0`
   */
  ACHIEVE001_ACHIEVE001: number;

  /**
   * ### ACHIEVE002_ACHIEVE002
   * - default value: `0`
   */
  ACHIEVE002_ACHIEVE002: number;

  /**
   * ### ACHIEVE003_ACHIEVE003
   * - default value: `0`
   */
  ACHIEVE003_ACHIEVE003: number;

  /**
   * ### ACHIEVE004_ACHIEVE004
   * - default value: `0`
   */
  ACHIEVE004_ACHIEVE004: number;

  /**
   * ### ACHIEVE005_ACHIEVE005
   * - default value: `0`
   */
  ACHIEVE005_ACHIEVE005: number;

  /**
   * ### ACHIEVE006_ACHIEVE006
   * - default value: `0`
   */
  ACHIEVE006_ACHIEVE006: number;

  /**
   * ### ACHIEVE007_ACHIEVE007
   * - default value: `0`
   */
  ACHIEVE007_ACHIEVE007: number;

  /**
   * ### ACHIEVE008_ACHIEVE008
   * - default value: `0`
   */
  ACHIEVE008_ACHIEVE008: number;

  /**
   * ### ACHIEVE009_ACHIEVE009
   * - default value: `0`
   */
  ACHIEVE009_ACHIEVE009: number;

  /**
   * ### ACHIEVE010_ACHIEVE010
   * - default value: `0`
   */
  ACHIEVE010_ACHIEVE010: number;

  /**
   * ### ACHIEVE011_ACHIEVE011
   * - default value: `0`
   */
  ACHIEVE011_ACHIEVE011: number;

  /**
   * ### ACHIEVE012_ACHIEVE012
   * - default value: `0`
   */
  ACHIEVE012_ACHIEVE012: number;

  /**
   * ### ACHIEVE013_ACHIEVE013
   * - default value: `0`
   */
  ACHIEVE013_ACHIEVE013: number;

  /**
   * ### ACHIEVE014_ACHIEVE014
   * - default value: `0`
   */
  ACHIEVE014_ACHIEVE014: number;

  /**
   * ### ACHIEVE015_ACHIEVE015
   * - default value: `0`
   */
  ACHIEVE015_ACHIEVE015: number;

  /**
   * ### ACHIEVE016_ACHIEVE016
   * - default value: `0`
   */
  ACHIEVE016_ACHIEVE016: number;

  /**
   * ### ACHIEVE017_ACHIEVE017
   * - default value: `0`
   */
  ACHIEVE017_ACHIEVE017: number;

  /**
   * ### ACHIEVE018_ACHIEVE018
   * - default value: `0`
   */
  ACHIEVE018_ACHIEVE018: number;

  /**
   * ### ACHIEVE019_ACHIEVE019
   * - default value: `0`
   */
  ACHIEVE019_ACHIEVE019: number;

  /**
   * ### ACHIEVE020_ACHIEVE020
   * - default value: `0`
   */
  ACHIEVE020_ACHIEVE020: number;

  /**
   * ### ACHIEVE021_ACHIEVE021
   * - default value: `0`
   */
  ACHIEVE021_ACHIEVE021: number;

  /**
   * ### ACHIEVE022_ACHIEVE022
   * - default value: `0`
   */
  ACHIEVE022_ACHIEVE022: number;

  /**
   * ### ACHIEVE023_ACHIEVE023
   * - default value: `0`
   */
  ACHIEVE023_ACHIEVE023: number;

  /**
   * ### ACHIEVE024_ACHIEVE024
   * - default value: `0`
   */
  ACHIEVE024_ACHIEVE024: number;

  /**
   * ### ACHIEVE025_ACHIEVE025
   * - default value: `0`
   */
  ACHIEVE025_ACHIEVE025: number;

  /**
   * ### ACHIEVE026_ACHIEVE026
   * - default value: `0`
   */
  ACHIEVE026_ACHIEVE026: number;

  /**
   * ### ACHIEVE027_ACHIEVE027
   * - default value: `0`
   */
  ACHIEVE027_ACHIEVE027: number;

  /**
   * ### ACHIEVE028_ACHIEVE028
   * - default value: `0`
   */
  ACHIEVE028_ACHIEVE028: number;

  /**
   * ### ACHIEVE029_ACHIEVE029
   * - default value: `0`
   */
  ACHIEVE029_ACHIEVE029: number;

  /**
   * ### ACHIEVE030_ACHIEVE030
   * - default value: `0`
   */
  ACHIEVE030_ACHIEVE030: number;

  /**
   * ### ACHIEVE031_ACHIEVE031
   * - default value: `0`
   */
  ACHIEVE031_ACHIEVE031: number;

  /**
   * ### ACHIEVE032_ACHIEVE032
   * - default value: `0`
   */
  ACHIEVE032_ACHIEVE032: number;

  /**
   * ### ACHIEVE033_ACHIEVE033
   * - default value: `0`
   */
  ACHIEVE033_ACHIEVE033: number;

  /**
   * ### ACHIEVE034_ACHIEVE034
   * - default value: `0`
   */
  ACHIEVE034_ACHIEVE034: number;

  /**
   * ### ACHIEVE035_ACHIEVE035
   * - default value: `0`
   */
  ACHIEVE035_ACHIEVE035: number;

  /**
   * ### ACHIEVE036_ACHIEVE036
   * - default value: `0`
   */
  ACHIEVE036_ACHIEVE036: number;
}

interface PUBGAchievements {
  /**
   * ### Last Survivor
   * Win a game 10 times.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE000: boolean;

  /**
   * ### Winner Winner Chicken Dinner!
   * Obtain a Chicken Dinner in Solo.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE001: boolean;

  /**
   * ### Dynamic Duo
   * Obtain a Chicken Dinner in Duos.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE002: boolean;

  /**
   * ### Fantastic Four
   * Obtain a Chicken Dinner in Squads.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE003: boolean;

  /**
   * ### Top 10
   * Reach the top 10 10 times.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE004: boolean;

  /**
   * ### Pacifist
   * Reach the top 10 without killing anyone.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE005: boolean;

  /**
   * ### CQB Master
   * Kill 200 players with a shotgun, a submachine gun, and/or a pistol.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE006: boolean;

  /**
   * ### CQB Expert
   * Kill 50 players with a shotgun, a submachine gun, and/or a pistol.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE007: boolean;

  /**
   * ### CQB Novice
   * Kill 10 players with a shotgun, a submachine gun, and/or a pistol.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE008: boolean;

  /**
   * ### Marksman Master
   * Kill 100 players with an assault rifle and/or a sniper rifle from over 100 meters away.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE009: boolean;

  /**
   * ### Marksman Expert
   * Kill 30 players with an assault rifle and/or a sniper rifle from over 100 meters away.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE010: boolean;

  /**
   * ### Marksman Novice
   * Kill 10 players with an assault rifle and/or a sniper rifle from over 100 meters away.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE011: boolean;

  /**
   * ### Nade King Master
   * Kill 50 players with grenades.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE012: boolean;

  /**
   * ### Nade King Expert
   * Kill 30 players with grenades.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE013: boolean;

  /**
   * ### Nade King Novice
   * Kill 10 players with grenades.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE014: boolean;

  /**
   * ### Long and Winding Road
   * Kill 1000 players by any means.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE015: boolean;

  /**
   * ### Collateral Damage
   * Kill 100 players by any means.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE016: boolean;

  /**
   * ### Devil Inside Me
   * Kill 10 players by any means.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE017: boolean;

  /**
   * ### Blood on My Hands
   * Kill a player by any means.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE018: boolean;

  /**
   * ### The First Rule Is…
   * Kill 20 players with bare hands.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE019: boolean;

  /**
   * ### Killing Spree
   * Kill at least 4 players in a single match.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE020: boolean;

  /**
   * ### Trigonometry Involved
   * Headshot and kill 10 enemy players with a sniper rifle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE021: boolean;

  /**
   * ### Okay, Now I'm Ready
   * Equip a Lv.3 Helmet, Military Vest, and Backpack in 10 matches.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE022: boolean;

  /**
   * ### First Blood
   * Get the first kill of a match.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE023: boolean;

  /**
   * ### Shoot the Knee
   * Kill 10 players with the crossbow.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE024: boolean;

  /**
   * ### First Come, First Served
   * Loot 50 items from the carepackage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE025: boolean;

  /**
   * ### Agent 48
   * Kill 50 players with suppressed weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE026: boolean;

  /**
   * ### Now You See Me, Now You Don't
   * Equip a ghillie suit for the first time.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE027: boolean;

  /**
   * ### Airborne
   * Jump out from an airplane 101 times.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE028: boolean;

  /**
   * ### Fury Road
   * Kill 10 players with a gun while in a vehicle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE029: boolean;

  /**
   * ### Guardian Angel
   * Revive a knocked-downed teammate.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE030: boolean;

  /**
   * ### Ghost
   * Equip a suppressed weapon in every weapon slot. Let's find out which weapon is suppressed!
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE031: boolean;

  /**
   * ### Don't Pan Me Bro!
   * Kill another player with the frying pan.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE032: boolean;

  /**
   * ### Fast and Furious
   * Kill 10 players by hitting them with a vehicle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE033: boolean;

  /**
   * ### You Complete Me
   * Wear the outfit of a dead player.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE034: boolean;

  /**
   * ### Cruising with the Enemy
   * Get into a vehicle where an enemy player is already in.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE035: boolean;

  /**
   * ### Health Junkie
   * Charge your boost gauge to the max with energy drink and painkiller overdose.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIVE036: boolean;
}
