// This file is autogenerated by a script

export interface CSSAdapter {
  stats: CSSStats;
  achievements: CSSAchievements;
}

interface CSSStats {
  /**
   * ### Enemy players killed
   * - default value: `0`
   */
  i_Number_Of_Kills: number;

  /**
   * ### Player Deaths
   * - default value: `0`
   */
  i_Number_Of_Deaths: number;

  /**
   * ### Time Played
   * - default value: `0`
   */
  i_Time_Played: number;

  /**
   * ### Bombs Planted
   * - default value: `0`
   */
  i_Number_Of_PlantedBombs: number;

  /**
   * ### Bombs Defused
   * - default value: `0`
   */
  i_Number_Of_DefusedBombs: number;

  /**
   * ### Rounds Won
   * - default value: `0`
   */
  total_wins: number;

  /**
   * ### Damage Done to Enemies
   * - default value: `0`
   */
  i_Damage_Done: number;

  /**
   * ### Money Earned
   * - default value: `0`
   */
  i_Money_Earned: number;

  /**
   * ### Hostages Rescued
   * - default value: `0`
   */
  i_Number_Of_RescuedHostages: number;

  /**
   * ### Knife Kills
   * - default value: `0`
   */
  total_kills_knife: number;

  /**
   * ### HE Grenade Kills
   * - default value: `0`
   */
  total_kills_hegrenade: number;

  /**
   * ### 9x19 Sidearm Kills
   * - default value: `0`
   */
  total_kills_glock: number;

  /**
   * ### KM Tactical .45 Kills
   * - default value: `0`
   */
  total_kills_usp: number;

  /**
   * ### 228 Compact Kills
   * - default value: `0`
   */
  total_kills_p228: number;

  /**
   * ### Night Hawk .50c Kills
   * - default value: `0`
   */
  total_kills_deagle: number;

  /**
   * ### .40 Dual Elites Kills
   * - default value: `0`
   */
  total_kills_elite: number;

  /**
   * ### ES Five-Seven Kills
   * - default value: `0`
   */
  total_kills_fiveseven: number;

  /**
   * ### M3 Super 90 Kills
   * - default value: `0`
   */
  total_kills_m3: number;

  /**
   * ### XM1014 Kills
   * - default value: `0`
   */
  total_kills_xm1014: number;

  /**
   * ### Ingram Mac-10 Kills
   * - default value: `0`
   */
  total_kills_mac10: number;

  /**
   * ### Schmidt Machine Pistol Kills
   * - default value: `0`
   */
  total_kills_tmp: number;

  /**
   * ### KM Sub-Machine Gun Kills
   * - default value: `0`
   */
  total_kills_mp5navy: number;

  /**
   * ### KM UMP45 Kills
   * - default value: `0`
   */
  total_kills_ump45: number;

  /**
   * ### ES C90 Kills
   * - default value: `0`
   */
  total_kills_p90: number;

  /**
   * ### Magnum Sniper Rifle Kills
   * - default value: `0`
   */
  total_kills_awp: number;

  /**
   * ### CV-47 Kills
   * - default value: `0`
   */
  total_kills_ak47: number;

  /**
   * ### Maverick M4A1 Kills
   * - default value: `0`
   */
  total_kills_m4a1: number;

  /**
   * ### Bullpup Kills
   * - default value: `0`
   */
  total_kills_aug: number;

  /**
   * ### Krieg 552 Kills
   * - default value: `0`
   */
  total_kills_sg552: number;

  /**
   * ### Krieg 550 Commando Kills
   * - default value: `0`
   */
  total_kills_sg550: number;

  /**
   * ### IDF Defender Kills
   * - default value: `0`
   */
  total_kills_galil: number;

  /**
   * ### Clarion 5.56 Kills
   * - default value: `0`
   */
  total_kills_famas: number;

  /**
   * ### Schmidt Scout Kills
   * - default value: `0`
   */
  total_kills_scout: number;

  /**
   * ### D3/AU-1 Kills
   * - default value: `0`
   */
  total_kills_g3sg1: number;

  /**
   * ### M249 Kills
   * - default value: `0`
   */
  total_kills_m249: number;

  /**
   * ### Headshots
   * - default value: `0`
   */
  total_kills_headshot: number;

  /**
   * ### Kills with enemy weapons
   * - default value: `0`
   */
  total_kills_enemy_weapon: number;

  /**
   * ### Pistol Rounds Won
   * - default value: `0`
   */
  total_wins_pistolround: number;

  /**
   * ### Decal Sprays
   * - default value: `0`
   */
  total_decal_sprays: number;

  /**
   * ### total_wins_map_cs_assault
   * - default value: `0`
   */
  total_wins_map_cs_assault: number;

  /**
   * ### total_wins_map_cs_compound
   * - default value: `0`
   */
  total_wins_map_cs_compound: number;

  /**
   * ### total_wins_map_cs_havana
   * - default value: `0`
   */
  total_wins_map_cs_havana: number;

  /**
   * ### total_wins_map_cs_italy
   * - default value: `0`
   */
  total_wins_map_cs_italy: number;

  /**
   * ### total_wins_map_cs_militia
   * - default value: `0`
   */
  total_wins_map_cs_militia: number;

  /**
   * ### total_wins_map_cs_office
   * - default value: `0`
   */
  total_wins_map_cs_office: number;

  /**
   * ### total_wins_map_de_aztec
   * - default value: `0`
   */
  total_wins_map_de_aztec: number;

  /**
   * ### total_wins_map_de_cbble
   * - default value: `0`
   */
  total_wins_map_de_cbble: number;

  /**
   * ### total_wins_map_de_chateau
   * - default value: `0`
   */
  total_wins_map_de_chateau: number;

  /**
   * ### total_wins_map_de_dust2
   * - default value: `0`
   */
  total_wins_map_de_dust2: number;

  /**
   * ### total_wins_map_de_dust
   * - default value: `0`
   */
  total_wins_map_de_dust: number;

  /**
   * ### total_wins_map_de_inferno
   * - default value: `0`
   */
  total_wins_map_de_inferno: number;

  /**
   * ### total_wins_map_de_nuke
   * - default value: `0`
   */
  total_wins_map_de_nuke: number;

  /**
   * ### total_wins_map_de_piranesi
   * - default value: `0`
   */
  total_wins_map_de_piranesi: number;

  /**
   * ### total_wins_map_de_port
   * - default value: `0`
   */
  total_wins_map_de_port: number;

  /**
   * ### total_wins_map_de_prodigy
   * - default value: `0`
   */
  total_wins_map_de_prodigy: number;

  /**
   * ### total_wins_map_de_tides
   * - default value: `0`
   */
  total_wins_map_de_tides: number;

  /**
   * ### total_wins_map_de_train
   * - default value: `0`
   */
  total_wins_map_de_train: number;

  /**
   * ### Weapons Donated
   * - default value: `0`
   */
  total_weapons_donated: number;

  /**
   * ### Windows Broken
   * - default value: `0`
   */
  i_Number_Of_BrokenWindows: number;

  /**
   * ### Blind Ememies Killed
   * - default value: `0`
   */
  total_kills_enemy_blinded: number;

  /**
   * ### Knife Fights Won
   * - default value: `0`
   */
  total_kills_knife_fight: number;

  /**
   * ### Zoomed Snipers Killed
   * - default value: `0`
   */
  total_kills_against_zoomed_sniper: number;

  /**
   * ### Damage During Nightvision
   * - default value: `0`
   */
  total_nightvision_damage: number;

  /**
   * ### Dominations
   * - default value: `0`
   */
  total_dominations: number;

  /**
   * ### Domination Overkills
   * - default value: `0`
   */
  total_domination_overkills: number;

  /**
   * ### Revenges
   * - default value: `0`
   */
  total_revenges: number;

  /**
   * ### Shots Hit
   * - default value: `0`
   */
  i_NumShotsHit: number;

  /**
   * ### Shots Fired
   * - default value: `0`
   */
  i_NumShotsFired: number;

  /**
   * ### Rounds Played
   * - default value: `0`
   */
  i_Total_Rounds: number;

  /**
   * ### total_shots_deagle
   * - default value: `0`
   */
  total_shots_deagle: number;

  /**
   * ### total_shots_usp
   * - default value: `0`
   */
  total_shots_usp: number;

  /**
   * ### total_shots_glock
   * - default value: `0`
   */
  total_shots_glock: number;

  /**
   * ### total_shots_p228
   * - default value: `0`
   */
  total_shots_p228: number;

  /**
   * ### total_shots_elite
   * - default value: `0`
   */
  total_shots_elite: number;

  /**
   * ### total_shots_fiveseven
   * - default value: `0`
   */
  total_shots_fiveseven: number;

  /**
   * ### total_shots_awp
   * - default value: `0`
   */
  total_shots_awp: number;

  /**
   * ### total_shots_ak47
   * - default value: `0`
   */
  total_shots_ak47: number;

  /**
   * ### total_shots_m4a1
   * - default value: `0`
   */
  total_shots_m4a1: number;

  /**
   * ### total_shots_aug
   * - default value: `0`
   */
  total_shots_aug: number;

  /**
   * ### total_shots_sg552
   * - default value: `0`
   */
  total_shots_sg552: number;

  /**
   * ### total_shots_sg550
   * - default value: `0`
   */
  total_shots_sg550: number;

  /**
   * ### total_shots_galil
   * - default value: `0`
   */
  total_shots_galil: number;

  /**
   * ### total_shots_famas
   * - default value: `0`
   */
  total_shots_famas: number;

  /**
   * ### total_shots_scout
   * - default value: `0`
   */
  total_shots_scout: number;

  /**
   * ### total_shots_g3sg1
   * - default value: `0`
   */
  total_shots_g3sg1: number;

  /**
   * ### total_shots_p90
   * - default value: `0`
   */
  total_shots_p90: number;

  /**
   * ### total_shots_mp5navy
   * - default value: `0`
   */
  total_shots_mp5navy: number;

  /**
   * ### total_shots_tmp
   * - default value: `0`
   */
  total_shots_tmp: number;

  /**
   * ### total_shots_mac10
   * - default value: `0`
   */
  total_shots_mac10: number;

  /**
   * ### total_shots_ump45
   * - default value: `0`
   */
  total_shots_ump45: number;

  /**
   * ### total_shots_m3
   * - default value: `0`
   */
  total_shots_m3: number;

  /**
   * ### total_shots_xm1014
   * - default value: `0`
   */
  total_shots_xm1014: number;

  /**
   * ### total_shots_m249
   * - default value: `0`
   */
  total_shots_m249: number;

  /**
   * ### total_hits_deagle
   * - default value: `0`
   */
  total_hits_deagle: number;

  /**
   * ### total_hits_usp
   * - default value: `0`
   */
  total_hits_usp: number;

  /**
   * ### total_hits_glock
   * - default value: `0`
   */
  total_hits_glock: number;

  /**
   * ### total_hits_p228
   * - default value: `0`
   */
  total_hits_p228: number;

  /**
   * ### total_hits_elite
   * - default value: `0`
   */
  total_hits_elite: number;

  /**
   * ### total_hits_fiveseven
   * - default value: `0`
   */
  total_hits_fiveseven: number;

  /**
   * ### total_hits_awp
   * - default value: `0`
   */
  total_hits_awp: number;

  /**
   * ### total_hits_ak47
   * - default value: `0`
   */
  total_hits_ak47: number;

  /**
   * ### total_hits_m4a1
   * - default value: `0`
   */
  total_hits_m4a1: number;

  /**
   * ### total_hits_aug
   * - default value: `0`
   */
  total_hits_aug: number;

  /**
   * ### total_hits_sg552
   * - default value: `0`
   */
  total_hits_sg552: number;

  /**
   * ### total_hits_sg550
   * - default value: `0`
   */
  total_hits_sg550: number;

  /**
   * ### total_hits_galil
   * - default value: `0`
   */
  total_hits_galil: number;

  /**
   * ### total_hits_famas
   * - default value: `0`
   */
  total_hits_famas: number;

  /**
   * ### total_hits_scout
   * - default value: `0`
   */
  total_hits_scout: number;

  /**
   * ### total_hits_g3sg1
   * - default value: `0`
   */
  total_hits_g3sg1: number;

  /**
   * ### total_hits_p90
   * - default value: `0`
   */
  total_hits_p90: number;

  /**
   * ### total_hits_mp5navy
   * - default value: `0`
   */
  total_hits_mp5navy: number;

  /**
   * ### total_hits_tmp
   * - default value: `0`
   */
  total_hits_tmp: number;

  /**
   * ### total_hits_mac10
   * - default value: `0`
   */
  total_hits_mac10: number;

  /**
   * ### total_hits_ump45
   * - default value: `0`
   */
  total_hits_ump45: number;

  /**
   * ### total_hits_m3
   * - default value: `0`
   */
  total_hits_m3: number;

  /**
   * ### total_hits_xm1014
   * - default value: `0`
   */
  total_hits_xm1014: number;

  /**
   * ### total_hits_m249
   * - default value: `0`
   */
  total_hits_m249: number;

  /**
   * ### total_rounds_map_cs_assault
   * - default value: `0`
   */
  total_rounds_map_cs_assault: number;

  /**
   * ### total_rounds_map_cs_compound
   * - default value: `0`
   */
  total_rounds_map_cs_compound: number;

  /**
   * ### total_rounds_map_cs_havana
   * - default value: `0`
   */
  total_rounds_map_cs_havana: number;

  /**
   * ### total_rounds_map_cs_italy
   * - default value: `0`
   */
  total_rounds_map_cs_italy: number;

  /**
   * ### total_rounds_map_cs_militia
   * - default value: `0`
   */
  total_rounds_map_cs_militia: number;

  /**
   * ### total_rounds_map_cs_office
   * - default value: `0`
   */
  total_rounds_map_cs_office: number;

  /**
   * ### total_rounds_map_de_aztec
   * - default value: `0`
   */
  total_rounds_map_de_aztec: number;

  /**
   * ### total_rounds_map_de_cbble
   * - default value: `0`
   */
  total_rounds_map_de_cbble: number;

  /**
   * ### total_rounds_map_de_chateau
   * - default value: `0`
   */
  total_rounds_map_de_chateau: number;

  /**
   * ### total_rounds_map_de_dust2
   * - default value: `0`
   */
  total_rounds_map_de_dust2: number;

  /**
   * ### total_rounds_map_de_dust
   * - default value: `0`
   */
  total_rounds_map_de_dust: number;

  /**
   * ### total_rounds_map_de_inferno
   * - default value: `0`
   */
  total_rounds_map_de_inferno: number;

  /**
   * ### total_rounds_map_de_nuke
   * - default value: `0`
   */
  total_rounds_map_de_nuke: number;

  /**
   * ### total_rounds_map_de_piranesi
   * - default value: `0`
   */
  total_rounds_map_de_piranesi: number;

  /**
   * ### total_rounds_map_de_port
   * - default value: `0`
   */
  total_rounds_map_de_port: number;

  /**
   * ### total_rounds_map_de_prodigy
   * - default value: `0`
   */
  total_rounds_map_de_prodigy: number;

  /**
   * ### total_rounds_map_de_tides
   * - default value: `0`
   */
  total_rounds_map_de_tides: number;

  /**
   * ### total_rounds_map_de_train
   * - default value: `0`
   */
  total_rounds_map_de_train: number;

  /**
   * ### last_match_t_wins
   * - default value: `0`
   */
  last_match_t_wins: number;

  /**
   * ### last_match_ct_wins
   * - default value: `0`
   */
  last_match_ct_wins: number;

  /**
   * ### last_match_wins
   * - default value: `0`
   */
  last_match_wins: number;

  /**
   * ### last_match_max_players
   * - default value: `0`
   */
  last_match_max_players: number;

  /**
   * ### last_match_kills
   * - default value: `0`
   */
  last_match_kills: number;

  /**
   * ### last_match_deaths
   * - default value: `0`
   */
  last_match_deaths: number;

  /**
   * ### last_match_mvps
   * - default value: `0`
   */
  last_match_mvps: number;

  /**
   * ### last_match_favweapon_id
   * - default value: `0`
   */
  last_match_favweapon_id: number;

  /**
   * ### last_match_favweapon_shots
   * - default value: `0`
   */
  last_match_favweapon_shots: number;

  /**
   * ### last_match_favweapon_hits
   * - default value: `0`
   */
  last_match_favweapon_hits: number;

  /**
   * ### last_match_favweapon_kills
   * - default value: `0`
   */
  last_match_favweapon_kills: number;

  /**
   * ### last_match_damage
   * - default value: `0`
   */
  last_match_damage: number;

  /**
   * ### last_match_money_spent
   * - default value: `0`
   */
  last_match_money_spent: number;

  /**
   * ### last_match_dominations
   * - default value: `0`
   */
  last_match_dominations: number;

  /**
   * ### last_match_revenges
   * - default value: `0`
   */
  last_match_revenges: number;

  /**
   * ### total_mvps
   * - default value: `0`
   */
  total_mvps: number;

  /**
   * ### COLLECT_GIFTS_STAT
   * - default value: `0`
   */
  COLLECT_GIFTS_STAT: number;
}

interface CSSAchievements {
  /**
   * ### Someone Set Up Us The Bomb
   * Win a round by planting a bomb
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_PLANT: boolean;

  /**
   * ### Boomala Boomala
   * Plant 100 bombs
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_PLANT_LOW: boolean;

  /**
   * ### The Hurt Blocker
   * Defuse 100 bombs
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_DEFUSE_LOW: boolean;

  /**
   * ### Body Bagger
   * Kill 25 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_LOW: boolean;

  /**
   * ### Corpseman
   * Kill 500 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MED: boolean;

  /**
   * ### God of War
   * Kill 10,000 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_HIGH: boolean;

  /**
   * ### Second to None
   * Successfully defuse a bomb with less than one second remaining
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_DEFUSE_CLOSE_CALL: boolean;

  /**
   * ### Combat Ready
   * Defuse a bomb with a kit when it would have failed without one
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_DEFUSE_NEEDED_KIT: boolean;

  /**
   * ### Counter-Counter-Terrorist
   * Kill a CT while he is defusing the bomb
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_BOMB_DEFUSER: boolean;

  /**
   * ### Rite of First Defusal
   * Win a round by defusing a bomb
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_DEFUSE: boolean;

  /**
   * ### Short Fuse
   * Plant a bomb within 25 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_PLANT_IN_25_SECONDS: boolean;

  /**
   * ### Newb World Order
   * Win 10 rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_LOW: boolean;

  /**
   * ### Pro-moted
   * Win 200 rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_MED: boolean;

  /**
   * ### Leet-er of Men
   * Win 5000 rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_HIGH: boolean;

  /**
   * ### Points in Your Favor
   * Inflict 2,500 total points of damage to enemy players
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_LOW: boolean;

  /**
   * ### You've Made Your Points
   * Inflict 50,000 total points of damage to enemy players
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_MED: boolean;

  /**
   * ### A Million Points of Blight
   * Inflict 1,000,000 total points of damage to enemy players
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_HIGH: boolean;

  /**
   * ### Ballistic
   * Kill 5 enemy players within 15 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  KILLING_SPREE: boolean;

  /**
   * ### Lost and F0wnd
   * KIll an enemy player with a gun they dropped that round
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WITH_OWN_GUN: boolean;

  /**
   * ### Cowboy Diplomacy
   * Rescue 100 hostages
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_HOSTAGES_LOW: boolean;

  /**
   * ### SAR Czar
   * Rescue 500 hostages
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_HOSTAGES_MED: boolean;

  /**
   * ### Good Shepherd
   * Rescue all hostages in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_ALL_HOSTAGES: boolean;

  /**
   * ### Freed With Speed
   * Rescue all hostages within 90 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  FAST_HOSTAGE_RESCUE: boolean;

  /**
   * ### Ammo Conservation
   * Kill two enemy players with a single bullet
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_TWO_WITH_ONE_SHOT: boolean;

  /**
   * ### War Bonds
   * Earn $125,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_LOW: boolean;

  /**
   * ### Spoils of War
   * Earn $2,500,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_MED: boolean;

  /**
   * ### Blood Money
   * Earn $50,000,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_HIGH: boolean;

  /**
   * ### Premature Burial
   * Kill an enemy with a grenade after you've died
   * - default value: `false`
   * - hidden: `false`
   */
  DEAD_GRENADE_KILL: boolean;

  /**
   * ### Night Hawk .50c Expert
   * Kill 200 enemy players with the Night Hawk .50c
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_DEAGLE: boolean;

  /**
   * ### KM Tactical .45 Expert
   * Kill 200 enemy players with the KM Tactical .45
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_USP: boolean;

  /**
   * ### 9x19 Sidearm Expert
   * Kill 200 enemy players with the 9x19 Sidearm
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_GLOCK: boolean;

  /**
   * ### 228 Compact Expert
   * Kill 200 enemy players with the 228 Compact
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_P228: boolean;

  /**
   * ### .40 Dual Elites Expert
   * Kill 100 enemy players with the .40 Dual Elites
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_ELITE: boolean;

  /**
   * ### ES Five-Seven Expert
   * Kill 100 enemy players with the ES Five-Seven
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_FIVESEVEN: boolean;

  /**
   * ### Pistol Master
   * Unlock all 6 Pistol kill achievements
   * - default value: `false`
   * - hidden: `false`
   */
  META_PISTOL: boolean;

  /**
   * ### Magnum Sniper Rifle Expert
   * Kill 1,000 enemy players with the Magnum Sniper Rifle
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AWP: boolean;

  /**
   * ### CV-47 Expert
   * Kill 1,000 enemy players with the CV-47
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AK47: boolean;

  /**
   * ### Maverick M4A1 Carbine Expert
   * Kill 1,000 enemy players with the Maverick M4A1 Carbine
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_M4A1: boolean;

  /**
   * ### Bullpup Expert
   * Kill 500 enemy players with the Bullpup
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AUG: boolean;

  /**
   * ### Krieg 552 Expert
   * Kill 500 enemy players with the Krieg 552
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SG552: boolean;

  /**
   * ### Krieg 550 Commando Expert
   * Kill 500 enemy players with the Krieg 550 Commando
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SG550: boolean;

  /**
   * ### IDF Defender Expert
   * Kill 500 enemy players with the IDF Defender
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_GALIL: boolean;

  /**
   * ### Clarion 5.56 Expert
   * Kill 500 enemy players with the Clarion 5.56
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_FAMAS: boolean;

  /**
   * ### Schmidt Scout Expert
   * Kill 1,000 enemy players with the Schmidt Scout
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SCOUT: boolean;

  /**
   * ### D3/AU-1 Expert
   * Kill 500 enemy players with the D3/AU-1
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_G3SG1: boolean;

  /**
   * ### Rifle Master
   * Unlock all 10 rifle kill achievements
   * - default value: `false`
   * - hidden: `false`
   */
  META_RIFLE: boolean;

  /**
   * ### ES C90 Expert
   * Kill 1,000 enemy players with the ES C90
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_P90: boolean;

  /**
   * ### KM Sub-Machine Gun Expert
   * Kill 1,000 enemy players with the KM Sub-Machine Gun
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MP5NAVY: boolean;

  /**
   * ### Schmidt Machine Pistol Expert
   * Kill 500 enemy players with the Schmidt Machine Pistol
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_TMP: boolean;

  /**
   * ### Ingram Mac-10 Expert
   * Kill 500 enemy players with the Ingram Mac-10
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MAC10: boolean;

  /**
   * ### KM UMP45 Expert
   * Kill 1,000 enemy players with the KM UMP45
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_UMP45: boolean;

  /**
   * ### Sub-Machine Gun Master
   * Unlock all 5 sub-machine gun kill achievements
   * - default value: `false`
   * - hidden: `false`
   */
  META_SMG: boolean;

  /**
   * ### Leone 12 Gauge Super Expert
   * Kill 200 enemy players with the Leone 12 Gauge Super
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_M3: boolean;

  /**
   * ### Leone YG1265 Auto Shotgun Expert
   * Kill 200 enemy players with the Leone YG1265 Auto Shotgun
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_XM1014: boolean;

  /**
   * ### Shotgun Master
   * Unlock both shotgun kill achievements
   * - default value: `false`
   * - hidden: `false`
   */
  META_SHOTGUN: boolean;

  /**
   * ### HE Grenade Expert
   * Kill 500 enemy players with the HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_HEGRENADE: boolean;

  /**
   * ### Knife Expert
   * Kill 100 enemy players with the knife
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_KNIFE: boolean;

  /**
   * ### M249 Expert
   * Kill 500 enemy players with the M249
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_M249: boolean;

  /**
   * ### Master At Arms
   * Unlock every weapon kill achievement
   * - default value: `false`
   * - hidden: `false`
   */
  META_WEAPONMASTER: boolean;

  /**
   * ### The Cleaner
   * Kill the entire enemy team (with at least 5 players) in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_TEAM: boolean;

  /**
   * ### Variety Hour
   * Get kills with 5 different guns in a round
   * - default value: `false`
   * - hidden: `false`
   */
  KILLS_WITH_MULTIPLE_GUNS: boolean;

  /**
   * ### Dead Shepherd
   * Kill an enemy player who is leading the hostages without injuring any hostages
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_HOSTAGE_RESCUER: boolean;

  /**
   * ### War of Attrition
   * Be the last player alive in a round (with at least 5 players on your team)
   * - default value: `false`
   * - hidden: `false`
   */
  LAST_PLAYER_ALIVE: boolean;

  /**
   * ### Magic Bullet
   * Kill an enemy with the last bullet in your magazine (excluding sniper rifles)
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_LAST_BULLET: boolean;

  /**
   * ### Kill One, Get One Spree
   * Kill an enemy player who is on a killing spree
   * - default value: `false`
   * - hidden: `false`
   */
  KILLING_SPREE_ENDER: boolean;

  /**
   * ### A World of Pane
   * Shoot out 14 windows in a single round on cs_office
   * - default value: `false`
   * - hidden: `false`
   */
  BREAK_WINDOWS: boolean;

  /**
   * ### Battle Sight Zero
   * Kill 250 enemy players with headshots
   * - default value: `false`
   * - hidden: `false`
   */
  HEADSHOTS: boolean;

  /**
   * ### Primer
   * Do at least 95% damage to an enemy who is then killed by a another player
   * - default value: `false`
   * - hidden: `false`
   */
  DAMAGE_NO_KILL: boolean;

  /**
   * ### Finishing Schooled
   * Kill an enemy player who has been reduced to less than 5% health by other players
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_LOW_DAMAGE: boolean;

  /**
   * ### Shot With Their Pants Down
   * Kill an enemy player while they are reloading
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_RELOADING: boolean;

  /**
   * ### Blind Ambition
   * Kill a total of 25 enemy players blinded by flashbangs
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_BLINDED: boolean;

  /**
   * ### Blind Fury
   * Kill an enemy player while you are blinded from a flashbang
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMIES_WHILE_BLIND: boolean;

  /**
   * ### Friendly Firearms
   * Kill 100 enemy players with enemy weapons
   * - default value: `false`
   * - hidden: `false`
   */
  KILLS_ENEMY_WEAPON: boolean;

  /**
   * ### Expert Marksman
   * Get a kill with every weapon
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WITH_EVERY_WEAPON: boolean;

  /**
   * ### Shrapnelproof
   * Take 80 points of damage from enemy grenades and still survive the round
   * - default value: `false`
   * - hidden: `false`
   */
  SURVIVE_GRENADE: boolean;

  /**
   * ### Make the Cut
   * Win a knife fight
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_KNIFE_FIGHTS_LOW: boolean;

  /**
   * ### The Bleeding Edge
   * Win 100 knife fights
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_KNIFE_FIGHTS_HIGH: boolean;

  /**
   * ### Defuse This!
   * Kill the defuser with an HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  KILLED_DEFUSER_WITH_GRENADE: boolean;

  /**
   * ### Safety First
   * Survive a shot to the head because you had the good sense to wear a helmet
   * - default value: `false`
   * - hidden: `false`
   */
  SURVIVED_HEADSHOT_DUE_TO_HELMET: boolean;

  /**
   * ### Hip Shot
   * Kill an enemy with an un-zoomed sniper rifle
   * - default value: `false`
   * - hidden: `false`
   */
  HIP_SHOT: boolean;

  /**
   * ### Eye to Eye
   * Kill a zoomed-in enemy sniper with a sniper rifle of your own
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPER_WITH_SNIPER: boolean;

  /**
   * ### Sknifed
   * Kill a zoomed-in enemy sniper with a knife
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPER_WITH_KNIFE: boolean;

  /**
   * ### Snipe Hunter
   * Kill 100 zoomed-in enemy snipers
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPERS: boolean;

  /**
   * ### Dead Man Stalking
   * Kill an enemy while at 1 health
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WHEN_AT_LOW_HEALTH: boolean;

  /**
   * ### Three the Hard Way
   * Kill 3 enemy players with a single HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  GRENADE_MULTIKILL: boolean;

  /**
   * ### Street Fighter
   * Kill an enemy player with a knife during the pistol round
   * - default value: `false`
   * - hidden: `false`
   */
  PISTOL_ROUND_KNIFE_KILL: boolean;

  /**
   * ### Blitzkrieg
   * Win a round in less than 30 seconds (against at least 5 enemy players)
   * - default value: `false`
   * - hidden: `false`
   */
  FAST_ROUND_WIN: boolean;

  /**
   * ### Piece Initiative
   * Win 5 Pistol Rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_LOW: boolean;

  /**
   * ### Give Piece a Chance
   * Win 25 Pistol Rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_MED: boolean;

  /**
   * ### Piece Treaty
   * Win 250 Pistol Rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_HIGH: boolean;

  /**
   * ### Clusterstruck
   * Kill 5 players in a C4 blast
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_MULTIKILL: boolean;

  /**
   * ### Wild Gooseman Chase
   * As the last living terrorist, distract a defuser long enough for the bomb to explode
   * - default value: `false`
   * - hidden: `false`
   */
  GOOSE_CHASE: boolean;

  /**
   * ### Blast Will and Testament
   * Win a round by picking up the bomb from a fallen comrade and successfully planting it
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_PLANT_AFTER_RECOVERY: boolean;

  /**
   * ### Target-Hardened
   * Survive damage from 5 different players within a round
   * - default value: `false`
   * - hidden: `false`
   */
  SURVIVE_MANY_ATTACKS: boolean;

  /**
   * ### Mercy Rule
   * Kill the entire opposing team without any members of your team dying
   * - default value: `false`
   * - hidden: `false`
   */
  LOSSLESS_EXTERMINATION: boolean;

  /**
   * ### Clean Sweep
   * Kill the entire opposing team without any members of your team taking any damage
   * - default value: `false`
   * - hidden: `false`
   */
  FLAWLESS_VICTORY: boolean;

  /**
   * ### Mad Props
   * Break 15 props in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  BREAK_PROPS: boolean;

  /**
   * ### Akimbo King
   * Use Dual Elites to kill an enemy player that also has Dual Elites equipped
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_DUAL_DUEL: boolean;

  /**
   * ### The Art of War
   * Spray 100 decals
   * - default value: `false`
   * - hidden: `false`
   */
  DECAL_SPRAYS: boolean;

  /**
   * ### Dead of Night
   * Do 5,000 damage with nightvision active
   * - default value: `false`
   * - hidden: `false`
   */
  NIGHTVISION_DAMAGE: boolean;

  /**
   * ### The Unstoppable Force
   * Kill 10 enemy players in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  UNSTOPPABLE_FORCE: boolean;

  /**
   * ### The Immovable Object
   * Kill an enemy player who has just killed 10 of your teammates in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  IMMOVABLE_OBJECT: boolean;

  /**
   * ### Head Shred Redemption
   * Kill 5 enemy players with headshots in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  HEADSHOTS_IN_ROUND: boolean;

  /**
   * ### Assault Map Veteran
   * Win 100 rounds on the CS_Assault map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_ASSAULT: boolean;

  /**
   * ### Compound Map Veteran
   * Win 100 rounds on the CS_Compound map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_COMPOUND: boolean;

  /**
   * ### Havana Map Veteran
   * Win 100 rounds on the CS_Havana map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_HAVANA: boolean;

  /**
   * ### Italy Map Veteran
   * Win 100 rounds on the CS_Italy map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_ITALY: boolean;

  /**
   * ### Militia Map Veteran
   * Win 100 rounds on the CS_Militia map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_MILITIA: boolean;

  /**
   * ### Office Map Veteran
   * Win 100 rounds on the CS_Office map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_OFFICE: boolean;

  /**
   * ### Aztec Map Veteran
   * Win 100 rounds on the DE_Aztec map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_AZTEC: boolean;

  /**
   * ### Cobblestone Map Veteran
   * Win 100 rounds on the DE_Cbble map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_CBBLE: boolean;

  /**
   * ### Chateau Map Veteran
   * Win 100 rounds on the DE_Chateau map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_CHATEAU: boolean;

  /**
   * ### Dust Map Veteran
   * Win 100 rounds on the DE_Dust map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_DUST: boolean;

  /**
   * ### Dust2 Map Veteran
   * Win 100 rounds on the DE_Dust2 map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_DUST2: boolean;

  /**
   * ### Inferno Map Veteran
   * Win 100 rounds on the DE_Inferno map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_INFERNO: boolean;

  /**
   * ### Nuke Map Veteran
   * Win 100 rounds on the DE_Nuke map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_NUKE: boolean;

  /**
   * ### Piranesi Map Veteran
   * Win 100 rounds on the DE_Piranesi map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_PIRANESI: boolean;

  /**
   * ### Port Map Veteran
   * Win 100 rounds on the DE_Port map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_PORT: boolean;

  /**
   * ### Prodigy Map Veteran
   * Win 100 rounds on the DE_Prodigy map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_PRODIGY: boolean;

  /**
   * ### Tides Map Veteran
   * Win 100 rounds on the DE_Tides map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_TIDES: boolean;

  /**
   * ### Train Map Veteran
   * Win 100 rounds on the DE_Train map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_TRAIN: boolean;

  /**
   * ### Death From Above
   * Kill an enemy player while you are airborne
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WHILE_IN_AIR: boolean;

  /**
   * ### Bunny Hunt
   * Kill an airborne enemy
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_IN_AIR: boolean;

  /**
   * ### Aerial Necrobatics
   * Kill an airborne enemy while you are also airborne
   * - default value: `false`
   * - hidden: `false`
   */
  KILLER_AND_ENEMY_IN_AIR: boolean;

  /**
   * ### Black Bag Operation
   * Win a round while making no footstep noise and killing at least one enemy
   * - default value: `false`
   * - hidden: `false`
   */
  SILENT_WIN: boolean;

  /**
   * ### Cold War
   * Win a round without your team killing any enemy players
   * - default value: `false`
   * - hidden: `false`
   */
  BLOODLESS_VICTORY: boolean;

  /**
   * ### Killanthropist
   * Donate 100 weapons to your teammates
   * - default value: `false`
   * - hidden: `false`
   */
  DONATE_WEAPONS: boolean;

  /**
   * ### The Frugal Beret
   * Win 10 rounds without dying and not spending any cash
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_WITHOUT_BUYING: boolean;

  /**
   * ### Defusus Interruptus
   * Stop defusing to kill a terrorist and then successfully finish defusing the bomb
   * - default value: `false`
   * - hidden: `false`
   */
  DEFUSE_DEFENSE: boolean;

  /**
   * ### Participation Award
   * Kill an enemy player within 3 seconds of them recovering a dropped bomb
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_BOMB_PICKUP: boolean;

  /**
   * ### Repeat Offender
   * Dominate an enemy player
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATIONS_LOW: boolean;

  /**
   * ### Decimator
   * Dominate a total of 10 enemy players
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATIONS_HIGH: boolean;

  /**
   * ### Overkill
   * Kill an opponent you are already dominating
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_LOW: boolean;

  /**
   * ### Command and Control
   * Get a total of 100 kills on enemy players you are dominating
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_HIGH: boolean;

  /**
   * ### Insurgent
   * Kill an enemy player that is dominating you
   * - default value: `false`
   * - hidden: `false`
   */
  REVENGES_LOW: boolean;

  /**
   * ### Can't Keep a Good Man Down
   * Kill a total of 20 enemy players that are dominating you
   * - default value: `false`
   * - hidden: `false`
   */
  REVENGES_HIGH: boolean;

  /**
   * ### Dressed to Kill
   * Start a round with all players on your team wearing the same uniform (at least 5 players)
   * - default value: `false`
   * - hidden: `false`
   */
  SAME_UNIFORM: boolean;

  /**
   * ### Hat Trick
   * Dominate three enemy players simultaneously
   * - default value: `false`
   * - hidden: `false`
   */
  CONCURRENT_DOMINATIONS: boolean;

  /**
   * ### Ten Angry Men
   * Get 10 kills on enemy players you are already dominating during a single match
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_MATCH: boolean;

  /**
   * ### Excessive Brutality
   * Kill an enemy player 4 additional times while you are dominating them
   * - default value: `false`
   * - hidden: `false`
   */
  EXTENDED_DOMINATION: boolean;

  /**
   * ### Spray and Pray
   * Kill two enemy players while you are blinded from a flashbang
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMIES_WHILE_BLIND_HARD: boolean;

  /**
   * ### Friendly Attire
   * Start a round on the same team as 4 of your friends, with all of you wearing the same outfit
   * - default value: `false`
   * - hidden: `false`
   */
  FRIENDS_SAME_UNIFORM: boolean;

  /**
   * ### The Road to Hell
   * Blind an enemy player who then kills a teammate
   * - default value: `false`
   * - hidden: `false`
   */
  CAUSE_FRIENDLY_FIRE_WITH_FLASHBANG: boolean;

  /**
   * ### Avenging Angel
   * Kill an enemy player in the same round as they kill a player on your friends list
   * - default value: `false`
   * - hidden: `false`
   */
  AVENGE_FRIEND: boolean;

  /**
   * ### Clan Warfare
   * Win a match of at least 10 players where the entirety of each team is composed of a single clan.
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_CLAN_MATCH: boolean;

  /**
   * ### Happy Camper
   * Get two kills standing in the same spot with a zoomed sniper rifle.
   * - default value: `false`
   * - hidden: `false`
   */
  SNIPE_TWO_FROM_SAME_SPOT: boolean;

  /**
   * ### Gift Grab
   * Collect three gifts dropped by opponents.
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_GIFTS: boolean;
}
