// This file is autogenerated by a script

export interface CSGOAdapter {
  stats: CSGOStats;
  achievements: CSGOAchievements;
}

interface CSGOStats {
  /**
   * ### Enemy players killed
   * - default value: `0`
   */
  total_kills: number;

  /**
   * ### Player Deaths
   * - default value: `0`
   */
  total_deaths: number;

  /**
   * ### Time Played
   * - default value: `0`
   */
  total_time_played: number;

  /**
   * ### Bombs Planted
   * - default value: `0`
   */
  total_planted_bombs: number;

  /**
   * ### Bombs Defused
   * - default value: `0`
   */
  total_defused_bombs: number;

  /**
   * ### Rounds Won
   * - default value: `0`
   */
  total_wins: number;

  /**
   * ### Damage Done to Enemies
   * - default value: `0`
   */
  total_damage_done: number;

  /**
   * ### Money Earned
   * - default value: `0`
   */
  total_money_earned: number;

  /**
   * ### Hostages Rescued
   * - default value: `0`
   */
  total_rescued_hostages: number;

  /**
   * ### Knife Kills
   * - default value: `0`
   */
  total_kills_knife: number;

  /**
   * ### HE Grenade Kills
   * - default value: `0`
   */
  total_kills_hegrenade: number;

  /**
   * ### 9x19 Sidearm Kills
   * - default value: `0`
   */
  total_kills_glock: number;

  /**
   * ### Desert Eagle .50c Kills
   * - default value: `0`
   */
  total_kills_deagle: number;

  /**
   * ### .40 Dual Elites Kills
   * - default value: `0`
   */
  total_kills_elite: number;

  /**
   * ### ES Five-Seven Kills
   * - default value: `0`
   */
  total_kills_fiveseven: number;

  /**
   * ### XM1014 Kills
   * - default value: `0`
   */
  total_kills_xm1014: number;

  /**
   * ### Ingram Mac-10 Kills
   * - default value: `0`
   */
  total_kills_mac10: number;

  /**
   * ### KM UMP45 Kills
   * - default value: `0`
   */
  total_kills_ump45: number;

  /**
   * ### ES C90 Kills
   * - default value: `0`
   */
  total_kills_p90: number;

  /**
   * ### Magnum Sniper Rifle Kills
   * - default value: `0`
   */
  total_kills_awp: number;

  /**
   * ### CV-47 Kills
   * - default value: `0`
   */
  total_kills_ak47: number;

  /**
   * ### Bullpup Kills
   * - default value: `0`
   */
  total_kills_aug: number;

  /**
   * ### IDF Defender Kills
   * - default value: `0`
   */
  total_kills_galil: number;

  /**
   * ### Clarion 5.56 Kills
   * - default value: `0`
   */
  total_kills_famas: number;

  /**
   * ### D3/AU-1 Kills
   * - default value: `0`
   */
  total_kills_g3sg1: number;

  /**
   * ### M249 Kills
   * - default value: `0`
   */
  total_kills_m249: number;

  /**
   * ### Headshots
   * - default value: `0`
   */
  total_kills_headshot: number;

  /**
   * ### Kills with enemy weapons
   * - default value: `0`
   */
  total_kills_enemy_weapon: number;

  /**
   * ### Pistol Rounds Won
   * - default value: `0`
   */
  total_wins_pistolround: number;

  /**
   * ### Decal Sprays
   * - default value: `0`
   */
  total_decal_sprays: number;

  /**
   * ### total_wins_map_cs_assault
   * - default value: `0`
   */
  total_wins_map_cs_assault: number;

  /**
   * ### total_wins_map_cs_italy
   * - default value: `0`
   */
  total_wins_map_cs_italy: number;

  /**
   * ### total_wins_map_cs_office
   * - default value: `0`
   */
  total_wins_map_cs_office: number;

  /**
   * ### total_wins_map_de_aztec
   * - default value: `0`
   */
  total_wins_map_de_aztec: number;

  /**
   * ### total_wins_map_de_cbble
   * - default value: `0`
   */
  total_wins_map_de_cbble: number;

  /**
   * ### total_wins_map_de_dust2
   * - default value: `0`
   */
  total_wins_map_de_dust2: number;

  /**
   * ### total_wins_map_de_dust
   * - default value: `0`
   */
  total_wins_map_de_dust: number;

  /**
   * ### total_wins_map_de_inferno
   * - default value: `0`
   */
  total_wins_map_de_inferno: number;

  /**
   * ### total_wins_map_de_nuke
   * - default value: `0`
   */
  total_wins_map_de_nuke: number;

  /**
   * ### total_wins_map_de_piranesi
   * - default value: `0`
   */
  total_wins_map_de_piranesi: number;

  /**
   * ### total_wins_map_de_prodigy
   * - default value: `0`
   */
  total_wins_map_de_prodigy: number;

  /**
   * ### total_wins_map_de_tides
   * - default value: `0`
   */
  total_wins_map_de_tides: number;

  /**
   * ### total_wins_map_de_train
   * - default value: `0`
   */
  total_wins_map_de_train: number;

  /**
   * ### Weapons Donated
   * - default value: `0`
   */
  total_weapons_donated: number;

  /**
   * ### Windows Broken
   * - default value: `0`
   */
  total_broken_windows: number;

  /**
   * ### Blind Ememies Killed
   * - default value: `0`
   */
  total_kills_enemy_blinded: number;

  /**
   * ### Knife Fights Won
   * - default value: `0`
   */
  total_kills_knife_fight: number;

  /**
   * ### Zoomed Snipers Killed
   * - default value: `0`
   */
  total_kills_against_zoomed_sniper: number;

  /**
   * ### Dominations
   * - default value: `0`
   */
  total_dominations: number;

  /**
   * ### Domination Overkills
   * - default value: `0`
   */
  total_domination_overkills: number;

  /**
   * ### Revenges
   * - default value: `0`
   */
  total_revenges: number;

  /**
   * ### Shots Hit
   * - default value: `0`
   */
  total_shots_hit: number;

  /**
   * ### Shots Fired
   * - default value: `0`
   */
  total_shots_fired: number;

  /**
   * ### Rounds Played
   * - default value: `0`
   */
  total_rounds_played: number;

  /**
   * ### total_shots_deagle
   * - default value: `0`
   */
  total_shots_deagle: number;

  /**
   * ### total_shots_glock
   * - default value: `0`
   */
  total_shots_glock: number;

  /**
   * ### total_shots_elite
   * - default value: `0`
   */
  total_shots_elite: number;

  /**
   * ### total_shots_fiveseven
   * - default value: `0`
   */
  total_shots_fiveseven: number;

  /**
   * ### total_shots_awp
   * - default value: `0`
   */
  total_shots_awp: number;

  /**
   * ### total_shots_ak47
   * - default value: `0`
   */
  total_shots_ak47: number;

  /**
   * ### total_shots_aug
   * - default value: `0`
   */
  total_shots_aug: number;

  /**
   * ### total_shots_galil
   * - default value: `0`
   */
  total_shots_galil: number;

  /**
   * ### total_shots_famas
   * - default value: `0`
   */
  total_shots_famas: number;

  /**
   * ### total_shots_g3sg1
   * - default value: `0`
   */
  total_shots_g3sg1: number;

  /**
   * ### total_shots_p90
   * - default value: `0`
   */
  total_shots_p90: number;

  /**
   * ### total_shots_mac10
   * - default value: `0`
   */
  total_shots_mac10: number;

  /**
   * ### total_shots_ump45
   * - default value: `0`
   */
  total_shots_ump45: number;

  /**
   * ### total_shots_xm1014
   * - default value: `0`
   */
  total_shots_xm1014: number;

  /**
   * ### total_shots_m249
   * - default value: `0`
   */
  total_shots_m249: number;

  /**
   * ### total_hits_deagle
   * - default value: `0`
   */
  total_hits_deagle: number;

  /**
   * ### total_hits_glock
   * - default value: `0`
   */
  total_hits_glock: number;

  /**
   * ### total_hits_elite
   * - default value: `0`
   */
  total_hits_elite: number;

  /**
   * ### total_hits_fiveseven
   * - default value: `0`
   */
  total_hits_fiveseven: number;

  /**
   * ### total_hits_awp
   * - default value: `0`
   */
  total_hits_awp: number;

  /**
   * ### total_hits_ak47
   * - default value: `0`
   */
  total_hits_ak47: number;

  /**
   * ### total_hits_aug
   * - default value: `0`
   */
  total_hits_aug: number;

  /**
   * ### total_hits_galil
   * - default value: `0`
   */
  total_hits_galil: number;

  /**
   * ### total_hits_famas
   * - default value: `0`
   */
  total_hits_famas: number;

  /**
   * ### total_hits_g3sg1
   * - default value: `0`
   */
  total_hits_g3sg1: number;

  /**
   * ### total_hits_p90
   * - default value: `0`
   */
  total_hits_p90: number;

  /**
   * ### total_hits_mac10
   * - default value: `0`
   */
  total_hits_mac10: number;

  /**
   * ### total_hits_ump45
   * - default value: `0`
   */
  total_hits_ump45: number;

  /**
   * ### total_hits_xm1014
   * - default value: `0`
   */
  total_hits_xm1014: number;

  /**
   * ### total_hits_m249
   * - default value: `0`
   */
  total_hits_m249: number;

  /**
   * ### total_rounds_map_cs_assault
   * - default value: `0`
   */
  total_rounds_map_cs_assault: number;

  /**
   * ### total_rounds_map_cs_italy
   * - default value: `0`
   */
  total_rounds_map_cs_italy: number;

  /**
   * ### total_rounds_map_cs_office
   * - default value: `0`
   */
  total_rounds_map_cs_office: number;

  /**
   * ### total_rounds_map_de_aztec
   * - default value: `0`
   */
  total_rounds_map_de_aztec: number;

  /**
   * ### total_rounds_map_de_cbble
   * - default value: `0`
   */
  total_rounds_map_de_cbble: number;

  /**
   * ### total_rounds_map_de_dust2
   * - default value: `0`
   */
  total_rounds_map_de_dust2: number;

  /**
   * ### total_rounds_map_de_dust
   * - default value: `0`
   */
  total_rounds_map_de_dust: number;

  /**
   * ### total_rounds_map_de_inferno
   * - default value: `0`
   */
  total_rounds_map_de_inferno: number;

  /**
   * ### total_rounds_map_de_nuke
   * - default value: `0`
   */
  total_rounds_map_de_nuke: number;

  /**
   * ### total_rounds_map_de_piranesi
   * - default value: `0`
   */
  total_rounds_map_de_piranesi: number;

  /**
   * ### total_rounds_map_de_prodigy
   * - default value: `0`
   */
  total_rounds_map_de_prodigy: number;

  /**
   * ### total_rounds_map_de_train
   * - default value: `0`
   */
  total_rounds_map_de_train: number;

  /**
   * ### last_match_t_wins
   * - default value: `0`
   */
  last_match_t_wins: number;

  /**
   * ### last_match_ct_wins
   * - default value: `0`
   */
  last_match_ct_wins: number;

  /**
   * ### last_match_wins
   * - default value: `0`
   */
  last_match_wins: number;

  /**
   * ### last_match_max_players
   * - default value: `0`
   */
  last_match_max_players: number;

  /**
   * ### last_match_kills
   * - default value: `0`
   */
  last_match_kills: number;

  /**
   * ### last_match_deaths
   * - default value: `0`
   */
  last_match_deaths: number;

  /**
   * ### last_match_mvps
   * - default value: `0`
   */
  last_match_mvps: number;

  /**
   * ### last_match_favweapon_id
   * - default value: `0`
   */
  last_match_favweapon_id: number;

  /**
   * ### last_match_favweapon_shots
   * - default value: `0`
   */
  last_match_favweapon_shots: number;

  /**
   * ### last_match_favweapon_hits
   * - default value: `0`
   */
  last_match_favweapon_hits: number;

  /**
   * ### last_match_favweapon_kills
   * - default value: `0`
   */
  last_match_favweapon_kills: number;

  /**
   * ### last_match_damage
   * - default value: `0`
   */
  last_match_damage: number;

  /**
   * ### last_match_money_spent
   * - default value: `0`
   */
  last_match_money_spent: number;

  /**
   * ### last_match_dominations
   * - default value: `0`
   */
  last_match_dominations: number;

  /**
   * ### last_match_revenges
   * - default value: `0`
   */
  last_match_revenges: number;

  /**
   * ### total_mvps
   * - default value: `0`
   */
  total_mvps: number;

  /**
   * ### total rounds won in lake
   * - default value: `0`
   */
  total_rounds_map_de_lake: number;

  /**
   * ### total rounds won in safehouse
   * - default value: `0`
   */
  total_rounds_map_de_safehouse: number;

  /**
   * ### total rounds won on sugarcane
   * - default value: `0`
   */
  total_rounds_map_de_sugarcane: number;

  /**
   * ### total rounds won on stmarc
   * - default value: `0`
   */
  total_rounds_map_de_stmarc: number;

  /**
   * ### total_rounds_map_de_bank
   * - default value: `0`
   */
  total_rounds_map_de_bank: number;

  /**
   * ### total rounds won on embassy
   * - default value: `0`
   */
  total_rounds_map_de_embassy: number;

  /**
   * ### total rounds won in short-train
   * - default value: `0`
   */
  total_rounds_map_de_shorttrain: number;

  /**
   * ### Demolition bombs placed
   * - default value: `0`
   */
  total_TR_planted_bombs: number;

  /**
   * ### Demolition bombs defused
   * - default value: `0`
   */
  total_TR_defused_bombs: number;

  /**
   * ### total rounds of Arsenal Mode won
   * - default value: `0`
   */
  total_gun_game_rounds_won: number;

  /**
   * ### total rounds of Arsenal Mode played
   * - default value: `0`
   */
  total_gun_game_rounds_played: number;

  /**
   * ### wins on map house
   * - default value: `0`
   */
  total_wins_map_de_house: number;

  /**
   * ### wins on map mill
   * - default value: `0`
   */
  total_wins_map_de_mill: number;

  /**
   * ### wins on map shacks
   * - default value: `0`
   */
  total_wins_map_de_shacks: number;

  /**
   * ### wins on map bank
   * - default value: `0`
   */
  total_wins_map_de_bank: number;

  /**
   * ### wins on map alleyway
   * - default value: `0`
   */
  total_wins_map_de_alleyway: number;

  /**
   * ### wins on map depot
   * - default value: `0`
   */
  total_wins_map_de_depot: number;

  /**
   * ### total_wins_map_de_vertigo
   * - default value: `0`
   */
  total_wins_map_de_vertigo: number;

  /**
   * ### wins on map balkan
   * - default value: `0`
   */
  total_wins_map_de_balkan: number;

  /**
   * ### rounds played on balkan
   * - default value: `0`
   */
  total_rounds_map_de_balkan: number;

  /**
   * ### wins on map monastery
   * - default value: `0`
   */
  total_wins_map_ar_monastery: number;

  /**
   * ### total rounds won in shoots
   * - default value: `0`
   */
  total_rounds_map_ar_shoots: number;

  /**
   * ### rounds played on map baggage
   * - default value: `0`
   */
  total_rounds_map_ar_baggage: number;

  /**
   * ### matches won on shoots
   * - default value: `0`
   */
  total_wins_map_ar_shoots: number;

  /**
   * ### matches won on baggage
   * - default value: `0`
   */
  total_wins_map_ar_baggage: number;

  /**
   * ### matches won on map lake
   * - default value: `0`
   */
  total_wins_map_de_lake: number;

  /**
   * ### matches won on map sugarcane
   * - default value: `0`
   */
  total_wins_map_de_sugarcane: number;

  /**
   * ### matches won on map stmarc
   * - default value: `0`
   */
  total_wins_map_de_stmarc: number;

  /**
   * ### total_matches_won_bank
   * - default value: `0`
   */
  total_matches_won_bank: number;

  /**
   * ### total matches won on embassy
   * - default value: `0`
   */
  total_wins_map_de_embassy: number;

  /**
   * ### total matches won on short-train
   * - default value: `0`
   */
  total_wins_map_de_shorttrain: number;

  /**
   * ### matches won on map safehouse
   * - default value: `0`
   */
  total_wins_map_de_safehouse: number;

  /**
   * ### total_matches_won
   * - default value: `0`
   */
  total_matches_won: number;

  /**
   * ### total_matches_drawn
   * - default value: `0`
   */
  total_matches_drawn: number;

  /**
   * ### total matches played
   * - default value: `0`
   */
  total_matches_played: number;

  /**
   * ### total_gg_matches_won
   * - default value: `0`
   */
  total_gg_matches_won: number;

  /**
   * ### Arsenal Mode matches played
   * - default value: `0`
   */
  total_gg_matches_played: number;

  /**
   * ### Arms Race matches won
   * - default value: `0`
   */
  total_progressive_matches_won: number;

  /**
   * ### total_select_matches_won
   * - default value: `0`
   */
  total_select_matches_won: number;

  /**
   * ### Demolition matches won
   * - default value: `0`
   */
  total_trbomb_matches_won: number;

  /**
   * ### contribution score
   * - default value: `0`
   */
  total_contribution_score: number;

  /**
   * ### last_match_contribution_score
   * - default value: `0`
   */
  last_match_contribution_score: number;

  /**
   * ### last_match_rounds
   * - default value: `0`
   */
  last_match_rounds: number;

  /**
   * ### total_kills_hkp2000
   * - default value: `0`
   */
  total_kills_hkp2000: number;

  /**
   * ### total_shots_hkp2000
   * - default value: `0`
   */
  total_shots_hkp2000: number;

  /**
   * ### total_hits_hkp2000
   * - default value: `0`
   */
  total_hits_hkp2000: number;

  /**
   * ### total_hits_p250
   * - default value: `0`
   */
  total_hits_p250: number;

  /**
   * ### total_kills_p250
   * - default value: `0`
   */
  total_kills_p250: number;

  /**
   * ### total_shots_p250
   * - default value: `0`
   */
  total_shots_p250: number;

  /**
   * ### total_shots_scar17
   * - default value: `0`
   */
  total_shots_scar17: number;

  /**
   * ### total_hits_scar17
   * - default value: `0`
   */
  total_hits_scar17: number;

  /**
   * ### total_kills_scar17
   * - default value: `0`
   */
  total_kills_scar17: number;

  /**
   * ### total_kills_sg556
   * - default value: `0`
   */
  total_kills_sg556: number;

  /**
   * ### total_shots_sg556
   * - default value: `0`
   */
  total_shots_sg556: number;

  /**
   * ### total_hits_sg556
   * - default value: `0`
   */
  total_hits_sg556: number;

  /**
   * ### total_hits_scar20
   * - default value: `0`
   */
  total_hits_scar20: number;

  /**
   * ### total_kills_scar20
   * - default value: `0`
   */
  total_kills_scar20: number;

  /**
   * ### total_shots_scar20
   * - default value: `0`
   */
  total_shots_scar20: number;

  /**
   * ### total_shots_ssg08
   * - default value: `0`
   */
  total_shots_ssg08: number;

  /**
   * ### total_hits_ssg08
   * - default value: `0`
   */
  total_hits_ssg08: number;

  /**
   * ### total_kills_ssg08
   * - default value: `0`
   */
  total_kills_ssg08: number;

  /**
   * ### total_shots_mp7
   * - default value: `0`
   */
  total_shots_mp7: number;

  /**
   * ### total_hits_mp7
   * - default value: `0`
   */
  total_hits_mp7: number;

  /**
   * ### total_kills_mp7
   * - default value: `0`
   */
  total_kills_mp7: number;

  /**
   * ### total_kills_mp9
   * - default value: `0`
   */
  total_kills_mp9: number;

  /**
   * ### total_shots_mp9
   * - default value: `0`
   */
  total_shots_mp9: number;

  /**
   * ### total_hits_mp9
   * - default value: `0`
   */
  total_hits_mp9: number;

  /**
   * ### total_hits_nova
   * - default value: `0`
   */
  total_hits_nova: number;

  /**
   * ### total_kills_nova
   * - default value: `0`
   */
  total_kills_nova: number;

  /**
   * ### total_shots_nova
   * - default value: `0`
   */
  total_shots_nova: number;

  /**
   * ### total_hits_negev
   * - default value: `0`
   */
  total_hits_negev: number;

  /**
   * ### total_kills_negev
   * - default value: `0`
   */
  total_kills_negev: number;

  /**
   * ### total_shots_negev
   * - default value: `0`
   */
  total_shots_negev: number;

  /**
   * ### total_shots_sawedoff
   * - default value: `0`
   */
  total_shots_sawedoff: number;

  /**
   * ### total_hits_sawedoff
   * - default value: `0`
   */
  total_hits_sawedoff: number;

  /**
   * ### total_kills_sawedoff
   * - default value: `0`
   */
  total_kills_sawedoff: number;

  /**
   * ### total_shots_bizon
   * - default value: `0`
   */
  total_shots_bizon: number;

  /**
   * ### total_hits_bizon
   * - default value: `0`
   */
  total_hits_bizon: number;

  /**
   * ### total_kills_bizon
   * - default value: `0`
   */
  total_kills_bizon: number;

  /**
   * ### total_kills_tec9
   * - default value: `0`
   */
  total_kills_tec9: number;

  /**
   * ### total_shots_tec9
   * - default value: `0`
   */
  total_shots_tec9: number;

  /**
   * ### total_hits_tec9
   * - default value: `0`
   */
  total_hits_tec9: number;

  /**
   * ### total_shots_mag7
   * - default value: `0`
   */
  total_shots_mag7: number;

  /**
   * ### total_hits_mag7
   * - default value: `0`
   */
  total_hits_mag7: number;

  /**
   * ### total_kills_mag7
   * - default value: `0`
   */
  total_kills_mag7: number;

  /**
   * ### Arsenal Mode contribution score
   * - default value: `0`
   */
  total_gun_game_contribution_score: number;

  /**
   * ### last_match_gg_contribution_score
   * - default value: `0`
   */
  last_match_gg_contribution_score: number;

  /**
   * ### total kills USP
   * - default value: `0`
   */
  total_kills_usp: number;

  /**
   * ### total kills p228
   * - default value: `0`
   */
  total_kills_p228: number;

  /**
   * ### total kills m4a4
   * - default value: `0`
   */
  total_kills_m4a1: number;

  /**
   * ### total kills sg552
   * - default value: `0`
   */
  total_kills_sg552: number;

  /**
   * ### total kills sg550
   * - default value: `0`
   */
  total_kills_sg550: number;

  /**
   * ### total kills galil AR
   * - default value: `0`
   */
  total_kills_galilar: number;

  /**
   * ### total kills scout
   * - default value: `0`
   */
  total_kills_scout: number;

  /**
   * ### total kills mp5 navy
   * - default value: `0`
   */
  total_kills_mp5navy: number;

  /**
   * ### total kills tmp
   * - default value: `0`
   */
  total_kills_tmp: number;

  /**
   * ### total kills m3
   * - default value: `0`
   */
  total_kills_m3: number;

  /**
   * ### total kills molotov
   * - default value: `0`
   */
  total_kills_molotov: number;

  /**
   * ### total kills decoy
   * - default value: `0`
   */
  total_kills_decoy: number;

  /**
   * ### total kills taser
   * - default value: `0`
   */
  total_kills_taser: number;

  /**
   * ### total shots usp
   * - default value: `0`
   */
  total_shots_usp: number;

  /**
   * ### total shots p228
   * - default value: `0`
   */
  total_shots_p228: number;

  /**
   * ### total shots m4a4
   * - default value: `0`
   */
  total_shots_m4a1: number;

  /**
   * ### total shots sg552
   * - default value: `0`
   */
  total_shots_sg552: number;

  /**
   * ### total shots sg550
   * - default value: `0`
   */
  total_shots_sg550: number;

  /**
   * ### total shots galil AR
   * - default value: `0`
   */
  total_shots_galilar: number;

  /**
   * ### total shots scout
   * - default value: `0`
   */
  total_shots_scout: number;

  /**
   * ### total shots mp5 navy
   * - default value: `0`
   */
  total_shots_mp5navy: number;

  /**
   * ### total shots tmp
   * - default value: `0`
   */
  total_shots_tmp: number;

  /**
   * ### total shots m3
   * - default value: `0`
   */
  total_shots_m3: number;

  /**
   * ### total shot taser
   * - default value: `0`
   */
  total_shots_taser: number;

  /**
   * ### total hits usp
   * - default value: `0`
   */
  total_hits_usp: number;

  /**
   * ### total hits p228
   * - default value: `0`
   */
  total_hits_p228: number;

  /**
   * ### total hits m4a4
   * - default value: `0`
   */
  total_hits_m4a1: number;

  /**
   * ### total hits sg552
   * - default value: `0`
   */
  total_hits_sg552: number;

  /**
   * ### total hits sg550
   * - default value: `0`
   */
  total_hits_sg550: number;

  /**
   * ### total hits galil AR
   * - default value: `0`
   */
  total_hits_galilar: number;

  /**
   * ### total hits scout
   * - default value: `0`
   */
  total_hits_scout: number;

  /**
   * ### total hits mp5 navy
   * - default value: `0`
   */
  total_hits_mp5navy: number;

  /**
   * ### total hits tmp
   * - default value: `0`
   */
  total_hits_tmp: number;

  /**
   * ### total hits m3
   * - default value: `0`
   */
  total_hits_m3: number;

  /**
   * ### total hits taser
   * - default value: `0`
   */
  total_hits_taser: number;

  /**
   * ### total rounds for monastery
   * - default value: `0`
   */
  total_rounds_map_ar_monastery: number;

  /**
   * ### total matches won on train
   * - default value: `0`
   */
  total_matches_won_train: number;

  /**
   * ### total rounds won in depot
   * - default value: `0`
   */
  total_rounds_map_de_depot: number;

  /**
   * ### total rounds won in vertigo
   * - default value: `0`
   */
  total_rounds_map_de_vertigo: number;

  /**
   * ### matches won on shoots
   * - default value: `0`
   */
  total_matches_won_shoots: number;

  /**
   * ### matches won on baggage
   * - default value: `0`
   */
  total_matches_won_baggage: number;

  /**
   * ### matches won on lake
   * - default value: `0`
   */
  total_matches_won_lake: number;

  /**
   * ### matches won on sugarcane
   * - default value: `0`
   */
  total_matches_won_sugarcane: number;

  /**
   * ### matches won on stmarc
   * - default value: `0`
   */
  total_matches_won_stmarc: number;

  /**
   * ### matches won on embassy
   * - default value: `0`
   */
  total_matches_won_embassy: number;

  /**
   * ### matches won on depot
   * - default value: `0`
   */
  total_matches_won_depot: number;

  /**
   * ### matches won on safehouse
   * - default value: `0`
   */
  total_matches_won_safehouse: number;

  /**
   * ### matches won on shorttrain
   * - default value: `0`
   */
  total_matches_won_shorttrain: number;

  /**
   * ### GI_lesson_csgo_instr_explain_buymenu
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_buymenu: number;

  /**
   * ### GI_lesson_csgo_instr_explain_buyarmor
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_buyarmor: number;

  /**
   * ### GI_lesson_csgo_instr_explain_plant_bomb
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_plant_bomb: number;

  /**
   * ### GI_lesson_csgo_instr_explain_bomb_carrier
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_bomb_carrier: number;

  /**
   * ### GI_lesson_bomb_sites_A
   * - default value: `0`
   */
  GI_lesson_bomb_sites_A: number;

  /**
   * ### GI_lesson_defuse_planted_bomb
   * - default value: `0`
   */
  GI_lesson_defuse_planted_bomb: number;

  /**
   * ### GI_lesson_csgo_instr_explain_follow_bomber
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_follow_bomber: number;

  /**
   * ### GI_lesson_csgo_instr_explain_pickup_bomb
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_pickup_bomb: number;

  /**
   * ### GI_lesson_csgo_instr_explain_prevent_bomb_pickup
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_prevent_bomb_pickup: number;

  /**
   * ### GI_lesson_csgo_instr_explain_defend_bomb
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_defend_bomb: number;

  /**
   * ### GI_lesson_Csgo_instr_explain_defuse_kit_carrier
   * - default value: `0`
   */
  GI_lesson_Csgo_instr_explain_defuse_kit_carrier: number;

  /**
   * ### GI_lesson_Csgo_cycle_weapons_kb
   * - default value: `0`
   */
  GI_lesson_Csgo_cycle_weapons_kb: number;

  /**
   * ### GI_lesson_Csgo_cycle_items_gp
   * - default value: `0`
   */
  GI_lesson_Csgo_cycle_items_gp: number;

  /**
   * ### GI_lesson_csgo_instr_explain_zoom
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_zoom: number;

  /**
   * ### GI_lesson_csgo_instr_explain_silencer
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_silencer: number;

  /**
   * ### GI_lesson_csgo_instr_explain_reload
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_reload: number;

  /**
   * ### GI_lesson_tr_explain_plant_bomb
   * - default value: `0`
   */
  GI_lesson_tr_explain_plant_bomb: number;

  /**
   * ### GI_lesson_csgo_instr_notify_level
   * - default value: `0`
   */
  GI_lesson_csgo_instr_notify_level: number;

  /**
   * ### GI_lesson_csgo_instr_notify_level_dem
   * - default value: `0`
   */
  GI_lesson_csgo_instr_notify_level_dem: number;

  /**
   * ### GI_lesson_csgo_instr_notify_earned_nade
   * - default value: `0`
   */
  GI_lesson_csgo_instr_notify_earned_nade: number;

  /**
   * ### GI_lesson_csgo_instr_notify_amd_knife
   * - default value: `0`
   */
  GI_lesson_csgo_instr_notify_amd_knife: number;

  /**
   * ### GI_lesson_csgo_instr_notify_amar_knife
   * - default value: `0`
   */
  GI_lesson_csgo_instr_notify_amar_knife: number;

  /**
   * ### GI_lesson_bomb_sites_B
   * - default value: `0`
   */
  GI_lesson_bomb_sites_B: number;

  /**
   * ### GI_lesson_version_number
   * - default value: `0`
   */
  GI_lesson_version_number: number;

  /**
   * ### GI_lesson_Csgo_cycle_weapons_gp
   * - default value: `0`
   */
  GI_lesson_Csgo_cycle_weapons_gp: number;

  /**
   * ### GI_lesson_find_planted_bomb
   * - default value: `0`
   */
  GI_lesson_find_planted_bomb: number;

  /**
   * ### GI_lesson_csgo_use_hostage_follow
   * - default value: `0`
   */
  GI_lesson_csgo_use_hostage_follow: number;

  /**
   * ### GI_lesson_csgo_hostage_follow_stop
   * - default value: `0`
   */
  GI_lesson_csgo_hostage_follow_stop: number;

  /**
   * ### GI_lesson_csgo_hostage_lead_to_hrz
   * - default value: `0`
   */
  GI_lesson_csgo_hostage_lead_to_hrz: number;

  /**
   * ### GI_lesson_csgo_instr_rescue_zone
   * - default value: `0`
   */
  GI_lesson_csgo_instr_rescue_zone: number;

  /**
   * ### GI_lesson_csgo_prevent_hostage_rescue
   * - default value: `0`
   */
  GI_lesson_csgo_prevent_hostage_rescue: number;

  /**
   * ### GI_lesson_csgo_switch_to_items_gp
   * - default value: `0`
   */
  GI_lesson_csgo_switch_to_items_gp: number;

  /**
   * ### GI_lesson_serverside_hint
   * - default value: `0`
   */
  GI_lesson_serverside_hint: number;

  /**
   * ### total_wins_map_cs_militia
   * - default value: `0`
   */
  total_wins_map_cs_militia: number;

  /**
   * ### total_rounds_map_cs_militia
   * - default value: `0`
   */
  total_rounds_map_cs_militia: number;

  /**
   * ### GI_lesson_csgo_instr_explain_inspect
   * - default value: `0`
   */
  GI_lesson_csgo_instr_explain_inspect: number;

  /**
   * ### Matches with Earned XP
   * - default value: `0`
   */
  steam_stat_xpearnedgames: number;

  /**
   * ### Official Competitive Wins
   * - default value: `0`
   */
  steam_stat_matchwinscomp: number;

  /**
   * ### Danger Zone Survivals
   * - default value: `0`
   */
  steam_stat_survivedz: number;
}

interface CSGOAchievements {  /**
   * ### Someone Set Up Us The Bomb
   * Win a round by planting a bomb
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_PLANT: boolean;

  /**
   * ### Boomala Boomala
   * Plant 100 bombs
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_PLANT_LOW: boolean;

  /**
   * ### The Hurt Blocker
   * Defuse 100 bombs successfully
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_DEFUSE_LOW: boolean;

  /**
   * ### Body Bagger
   * Kill 25 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_LOW: boolean;

  /**
   * ### Corpseman
   * Kill 500 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MED: boolean;

  /**
   * ### God of War
   * Kill 10,000 enemies
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_HIGH: boolean;

  /**
   * ### Second to None
   * Successfully defuse a bomb with less than one second remaining
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_DEFUSE_CLOSE_CALL: boolean;

  /**
   * ### Counter-Counter-Terrorist
   * Kill a Counter-Terrorist while he is defusing the bomb
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_BOMB_DEFUSER: boolean;

  /**
   * ### Rite of First Defusal
   * Win a round by defusing a bomb
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_DEFUSE: boolean;

  /**
   * ### Short Fuse
   * Plant a bomb within 25 seconds (excluding Demolition mode)
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_PLANT_IN_25_SECONDS: boolean;

  /**
   * ### Newb World Order
   * Win ten rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_LOW: boolean;

  /**
   * ### Pro-moted
   * Win 200 rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_MED: boolean;

  /**
   * ### Leet-er of Men
   * Win 5,000 rounds
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_HIGH: boolean;

  /**
   * ### Points in Your Favor
   * Inflict 2,500 total points of damage to enemies
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_LOW: boolean;

  /**
   * ### You've Made Your Points
   * Inflict 50,000 total points of damage to enemies
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_MED: boolean;

  /**
   * ### A Million Points of Blight
   * Inflict 1,000,000 total points of damage to enemies
   * - default value: `false`
   * - hidden: `false`
   */
  GIVE_DAMAGE_HIGH: boolean;

  /**
   * ### Ballistic
   * In Classic mode, kill four enemy players within fifteen seconds
   * - default value: `false`
   * - hidden: `false`
   */
  KILLING_SPREE: boolean;

  /**
   * ### Lost and F0wnd
   * Kill an enemy with a gun they dropped during the current round
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WITH_OWN_GUN: boolean;

  /**
   * ### Cowboy Diplomacy
   * Rescue 100 hostages
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_HOSTAGES_LOW: boolean;

  /**
   * ### SAR Czar
   * Rescue 500 hostages
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_HOSTAGES_MED: boolean;

  /**
   * ### Good Shepherd
   * Rescue all hostages in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  RESCUE_ALL_HOSTAGES: boolean;

  /**
   * ### Freed With Speed
   * Rescue all hostages within 90 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  FAST_HOSTAGE_RESCUE: boolean;

  /**
   * ### Ammo Conservation
   * Kill two enemy players with a single bullet
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_TWO_WITH_ONE_SHOT: boolean;

  /**
   * ### War Bonds
   * Earn $50,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_LOW: boolean;

  /**
   * ### Spoils of War
   * Earn $2,500,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_MED: boolean;

  /**
   * ### Blood Money
   * Earn $50,000,000 total cash
   * - default value: `false`
   * - hidden: `false`
   */
  EARN_MONEY_HIGH: boolean;

  /**
   * ### Premature Burial
   * Kill an enemy with a grenade after dying
   * - default value: `false`
   * - hidden: `false`
   */
  DEAD_GRENADE_KILL: boolean;

  /**
   * ### Desert Eagle Expert
   * Kill 200 enemies with the Desert Eagle
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_DEAGLE: boolean;

  /**
   * ### Glock-18 Expert
   * Kill 100 enemies with the Glock-18
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_GLOCK: boolean;

  /**
   * ### Dual Berettas Expert
   * Kill 25 enemies with the Dual Berettas
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_ELITE: boolean;

  /**
   * ### Five-SeveN Expert
   * Kill 25 enemies with the Five-SeveN
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_FIVESEVEN: boolean;

  /**
   * ### Pistol Master
   * Unlock all Pistol kill awards
   * - default value: `false`
   * - hidden: `false`
   */
  META_PISTOL: boolean;

  /**
   * ### AWP Expert
   * Kill 500 enemies with the AWP
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AWP: boolean;

  /**
   * ### AK-47 Expert
   * Kill 1,000 enemies with the AK-47
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AK47: boolean;

  /**
   * ### M4 AR Expert
   * Kill 1,000 enemies with an M4 Assault Rifle
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_M4A1: boolean;

  /**
   * ### AUG Expert
   * Kill 250 enemies with the AUG
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_AUG: boolean;

  /**
   * ### FAMAS Expert
   * Kill 100 enemies with the FAMAS
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_FAMAS: boolean;

  /**
   * ### G3SG1 Expert
   * Kill 100 enemies with the G3SG1
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_G3SG1: boolean;

  /**
   * ### Rifle Master
   * Unlock all rifle kill awards
   * - default value: `false`
   * - hidden: `false`
   */
  META_RIFLE: boolean;

  /**
   * ### P90 Expert
   * Kill 500 enemies with the P90
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_P90: boolean;

  /**
   * ### MAC-10 Expert
   * Kill 100 enemies with the MAC-10
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MAC10: boolean;

  /**
   * ### UMP-45 Expert
   * Kill 250 enemies with the UMP-45
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_UMP45: boolean;

  /**
   * ### Sub-Machine Gun Master
   * Unlock all sub-machine gun kill awards
   * - default value: `false`
   * - hidden: `false`
   */
  META_SMG: boolean;

  /**
   * ### XM1014 Expert
   * Kill 200 enemies with the XM1014
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_XM1014: boolean;

  /**
   * ### Shotgun Master
   * Unlock all shotgun kill awards
   * - default value: `false`
   * - hidden: `false`
   */
  META_SHOTGUN: boolean;

  /**
   * ### HE Grenade Expert
   * Kill 100 enemies with the HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_HEGRENADE: boolean;

  /**
   * ### Knife Expert
   * Kill 100 enemies with the knife
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_KNIFE: boolean;

  /**
   * ### M249 Expert
   * Kill 100 enemies with the M249
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_M249: boolean;

  /**
   * ### Master At Arms
   * Unlock every weapon kill award
   * - default value: `false`
   * - hidden: `false`
   */
  META_WEAPONMASTER: boolean;

  /**
   * ### The Cleaner
   * In Classic mode, kill five enemies in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_TEAM: boolean;

  /**
   * ### Variety Hour
   * Get kills with five different guns in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  KILLS_WITH_MULTIPLE_GUNS: boolean;

  /**
   * ### Dead Shepherd
   * Kill an enemy who is carrying a hostage
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_HOSTAGE_RESCUER: boolean;

  /**
   * ### War of Attrition
   * Be the last player alive in a round with five players on your team
   * - default value: `false`
   * - hidden: `false`
   */
  LAST_PLAYER_ALIVE: boolean;

  /**
   * ### Magic Bullet
   * Kill an enemy with the last bullet in your magazine (excluding sniper rifles and Zeus x27)
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_LAST_BULLET: boolean;

  /**
   * ### Kill One, Get One Spree
   * Kill an enemy player who has just killed four of your teammates within 15 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  KILLING_SPREE_ENDER: boolean;

  /**
   * ### A World of Pane
   * Shoot out 14 windows in a single round on Office
   * - default value: `false`
   * - hidden: `false`
   */
  BREAK_WINDOWS: boolean;

  /**
   * ### Battle Sight Zero
   * Kill 250 enemies with headshots
   * - default value: `false`
   * - hidden: `false`
   */
  HEADSHOTS: boolean;

  /**
   * ### Primer
   * Do at least 95% damage to an enemy who is then killed by a another player
   * - default value: `false`
   * - hidden: `false`
   */
  DAMAGE_NO_KILL: boolean;

  /**
   * ### Finishing Schooled
   * Kill an enemy who has been reduced to less than 5% health by other players
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_LOW_DAMAGE: boolean;

  /**
   * ### Shot With Their Pants Down
   * Kill an enemy while they are reloading
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_RELOADING: boolean;

  /**
   * ### Blind Ambition
   * Kill 25 enemies blinded by flashbangs
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_BLINDED: boolean;

  /**
   * ### Blind Fury
   * Kill an enemy while you are blinded from a flashbang
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMIES_WHILE_BLIND: boolean;

  /**
   * ### Friendly Firearms
   * Kill 100 enemies with enemy weapons
   * - default value: `false`
   * - hidden: `false`
   */
  KILLS_ENEMY_WEAPON: boolean;

  /**
   * ### Expert Marksman
   * Get a kill with every weapon
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WITH_EVERY_WEAPON: boolean;

  /**
   * ### Shrapnelproof
   * Take 80 points of damage from enemy grenades and still survive the round
   * - default value: `false`
   * - hidden: `false`
   */
  SURVIVE_GRENADE: boolean;

  /**
   * ### Make the Cut
   * Win a knife fight
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_KNIFE_FIGHTS_LOW: boolean;

  /**
   * ### The Bleeding Edge
   * Win 100 knife fights
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_KNIFE_FIGHTS_HIGH: boolean;

  /**
   * ### Defuse This!
   * Kill the defuser with an HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  KILLED_DEFUSER_WITH_GRENADE: boolean;

  /**
   * ### Hip Shot
   * Kill an enemy with an un-zoomed sniper rifle
   * - default value: `false`
   * - hidden: `false`
   */
  HIP_SHOT: boolean;

  /**
   * ### Eye to Eye
   * Kill a zoomed-in enemy sniper with a sniper rifle of your own
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPER_WITH_SNIPER: boolean;

  /**
   * ### Sknifed
   * Kill a zoomed-in enemy sniper with a knife
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPER_WITH_KNIFE: boolean;

  /**
   * ### Snipe Hunter
   * Kill 100 zoomed-in enemy snipers
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_SNIPERS: boolean;

  /**
   * ### Dead Man Stalking
   * Kill an enemy while at one health
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WHEN_AT_LOW_HEALTH: boolean;

  /**
   * ### Three the Hard Way
   * Kill three enemies with a single HE grenade
   * - default value: `false`
   * - hidden: `false`
   */
  GRENADE_MULTIKILL: boolean;

  /**
   * ### Street Fighter
   * Kill an enemy with a knife during the Pistol Round in a Classic match
   * - default value: `false`
   * - hidden: `false`
   */
  PISTOL_ROUND_KNIFE_KILL: boolean;

  /**
   * ### Blitzkrieg
   * Win a round against five enemies in less than thirty seconds
   * - default value: `false`
   * - hidden: `false`
   */
  FAST_ROUND_WIN: boolean;

  /**
   * ### Piece Initiative
   * Win 5 Pistol Rounds in Competitive Mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_LOW: boolean;

  /**
   * ### Give Piece a Chance
   * Win 25 Pistol Rounds in Competitive Mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_MED: boolean;

  /**
   * ### Piece Treaty
   * Win 250 Pistol Rounds in Competitive Mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_PISTOLROUNDS_HIGH: boolean;

  /**
   * ### Clusterstruck
   * Kill five enemies with a bomb you have planted
   * - default value: `false`
   * - hidden: `false`
   */
  BOMB_MULTIKILL: boolean;

  /**
   * ### Wild Gooseman Chase
   * As the last living Terrorist, distract a defuser long enough for the bomb to explode
   * - default value: `false`
   * - hidden: `false`
   */
  GOOSE_CHASE: boolean;

  /**
   * ### Blast Will and Testament
   * Win a round by picking up the bomb from a fallen comrade and successfully planting it
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_BOMB_PLANT_AFTER_RECOVERY: boolean;

  /**
   * ### Target-Hardened
   * Survive damage from five different enemies within a round
   * - default value: `false`
   * - hidden: `false`
   */
  SURVIVE_MANY_ATTACKS: boolean;

  /**
   * ### Mercy Rule
   * Kill the entire opposing team without any members of your team dying
   * - default value: `false`
   * - hidden: `false`
   */
  LOSSLESS_EXTERMINATION: boolean;

  /**
   * ### Clean Sweep
   * Kill the entire opposing team without any members of your team taking damage
   * - default value: `false`
   * - hidden: `false`
   */
  FLAWLESS_VICTORY: boolean;

  /**
   * ### Akimbo King
   * Use Dual Berettas to kill an enemy player that is also wielding Dual Berettas
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_DUAL_DUEL: boolean;

  /**
   * ### The Unstoppable Force
   * Kill four enemies within a single round
   * - default value: `false`
   * - hidden: `false`
   */
  UNSTOPPABLE_FORCE: boolean;

  /**
   * ### The Immovable Object
   * Kill an enemy who has killed four of your teammates within the current round
   * - default value: `false`
   * - hidden: `false`
   */
  IMMOVABLE_OBJECT: boolean;

  /**
   * ### Head Shred Redemption
   * Kill five enemy players with headshots in a single round
   * - default value: `false`
   * - hidden: `false`
   */
  HEADSHOTS_IN_ROUND: boolean;

  /**
   * ### Italy Map Veteran
   * Win 100 rounds on Italy
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_ITALY: boolean;

  /**
   * ### Office Map Veteran
   * Win 100 rounds on Office
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_CS_OFFICE: boolean;

  /**
   * ### Aztec Map Veteran
   * Win 100 rounds on Aztec
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_AZTEC: boolean;

  /**
   * ### Dust Map Veteran
   * Win 100 rounds on Dust
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_DUST: boolean;

  /**
   * ### Dust2 Map Veteran
   * Win 100 rounds on Dust2
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_DUST2: boolean;

  /**
   * ### Inferno Map Veteran
   * Win 100 rounds on Inferno
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_INFERNO: boolean;

  /**
   * ### Nuke Map Veteran
   * Win 100 rounds on Nuke
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_NUKE: boolean;

  /**
   * ### Shorttrain Map Veteran
   * Win five matches on Shorttrain
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_SHORTTRAIN: boolean;

  /**
   * ### Death From Above
   * Kill an enemy while you are airborne
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_WHILE_IN_AIR: boolean;

  /**
   * ### Bunny Hunt
   * Kill an airborne enemy
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_IN_AIR: boolean;

  /**
   * ### Aerial Necrobatics
   * Kill an airborne enemy while you are also airborne
   * - default value: `false`
   * - hidden: `false`
   */
  KILLER_AND_ENEMY_IN_AIR: boolean;

  /**
   * ### Black Bag Operation
   * Win a round without making any footstep noise, killing at least one enemy
   * - default value: `false`
   * - hidden: `false`
   */
  SILENT_WIN: boolean;

  /**
   * ### Cold War
   * Win a round in which no enemy players die
   * - default value: `false`
   * - hidden: `false`
   */
  BLOODLESS_VICTORY: boolean;

  /**
   * ### Killanthropist
   * Donate 100 weapons to your teammates
   * - default value: `false`
   * - hidden: `false`
   */
  DONATE_WEAPONS: boolean;

  /**
   * ### The Frugal Beret
   * Win ten rounds in a row without dying or spending any cash in Classic mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_ROUNDS_WITHOUT_BUYING: boolean;

  /**
   * ### Defusus Interruptus
   * Stop defusing the bomb long enough to kill an enemy, then successfully finish defusing it
   * - default value: `false`
   * - hidden: `false`
   */
  DEFUSE_DEFENSE: boolean;

  /**
   * ### Participation Award
   * Kill an enemy within three seconds after they recover a dropped bomb
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_BOMB_PICKUP: boolean;

  /**
   * ### Repeat Offender
   * Dominate an enemy
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATIONS_LOW: boolean;

  /**
   * ### Decimator
   * Dominate ten enemies
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATIONS_HIGH: boolean;

  /**
   * ### Overkill
   * Kill an enemy whom you are already dominating
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_LOW: boolean;

  /**
   * ### Command and Control
   * Kill 100 enemies whom you are already dominating
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_HIGH: boolean;

  /**
   * ### Insurgent
   * Kill an enemy who is dominating you
   * - default value: `false`
   * - hidden: `false`
   */
  REVENGES_LOW: boolean;

  /**
   * ### Can't Keep a Good Man Down
   * Kill 20 enemies who are dominating you
   * - default value: `false`
   * - hidden: `false`
   */
  REVENGES_HIGH: boolean;

  /**
   * ### Hat Trick
   * Dominate three enemies simultaneously
   * - default value: `false`
   * - hidden: `false`
   */
  CONCURRENT_DOMINATIONS: boolean;

  /**
   * ### Ten Angry Men
   * Kill 10 enemies you are already dominating during a single match
   * - default value: `false`
   * - hidden: `false`
   */
  DOMINATION_OVERKILLS_MATCH: boolean;

  /**
   * ### Excessive Brutality
   * Kill an enemy whom you are dominating four additional times
   * - default value: `false`
   * - hidden: `false`
   */
  EXTENDED_DOMINATION: boolean;

  /**
   * ### Spray and Pray
   * Kill two enemies while you are blinded from a flashbang
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMIES_WHILE_BLIND_HARD: boolean;

  /**
   * ### The Road to Hell
   * Blind an enemy player who then kills a teammate
   * - default value: `false`
   * - hidden: `false`
   */
  CAUSE_FRIENDLY_FIRE_WITH_FLASHBANG: boolean;

  /**
   * ### Avenging Angel
   * Kill an enemy who has killed a player on your friends list in the same round
   * - default value: `false`
   * - hidden: `false`
   */
  AVENGE_FRIEND: boolean;

  /**
   * ### Denied!
   * Kill a player who is on gold knife level in Arms Race Mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_KILL_KNIFER: boolean;

  /**
   * ### Marksman
   * Win a match on every Arms Race and Demolition map
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_EVERY_GUNGAME_MAP: boolean;

  /**
   * ### Shoots Vet
   * Win five matches in Arms Race Mode on Shoots
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_AR_SHOOTS: boolean;

  /**
   * ### Shorter Fuse
   * Plant five bombs in Demolition Mode
   * - default value: `false`
   * - hidden: `false`
   */
  TR_BOMB_PLANT_LOW: boolean;

  /**
   * ### Quick Cut
   * Defuse five bombs in Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  TR_BOMB_DEFUSE_LOW: boolean;

  /**
   * ### Vacation
   * Win five matches on Lake
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_LAKE: boolean;

  /**
   * ### My House
   * Win five matches on Safehouse
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_SAFEHOUSE: boolean;

  /**
   * ### Run of the Mill
   * Win five matches on Sugarcane
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_SUGARCANE: boolean;

  /**
   * ### Marcsman
   * Win five matches on St. Marc
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_STMARC: boolean;

  /**
   * ### Knife on Knife
   * Kill an enemy who is on gold knife level with your own knife in Arms Race Mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_KNIFE_KILL_KNIFER: boolean;

  /**
   * ### Level Playing Field
   * Kill an enemy who is on gold knife level with a sub-machine gun in Arms Race Mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_SMG_KILL_KNIFER: boolean;

  /**
   * ### Practice Practice Practice
   * Play 100 matches of Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_ROUNDS_LOW: boolean;

  /**
   * ### Gun Collector
   * Play 500 matches of Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_ROUNDS_MED: boolean;

  /**
   * ### King of the Kill
   * Play 5,000 matches of Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_ROUNDS_HIGH: boolean;

  /**
   * ### Gungamer
   * Win one match in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_GUN_GAME_ROUNDS_LOW: boolean;

  /**
   * ### Keep on Gunning
   * Win 25 matches in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_GUN_GAME_ROUNDS_MED: boolean;

  /**
   * ### Kill of the Century
   * Win 100 matches in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_GUN_GAME_ROUNDS_HIGH: boolean;

  /**
   * ### The Professional
   * Win 500 matches in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_GUN_GAME_ROUNDS_EXTREME: boolean;

  /**
   * ### Cold Pizza Eater
   * Win 1,000 matches in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_GUN_GAME_ROUNDS_ULTIMATE: boolean;

  /**
   * ### Tourist
   * Play a round on every Arms Race and Demolition map
   * - default value: `false`
   * - hidden: `false`
   */
  PLAY_EVERY_GUNGAME_MAP: boolean;

  /**
   * ### Rampage!
   * Win an Arms Race match without dying
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_RAMPAGE: boolean;

  /**
   * ### FIRST!
   * Be the first player to get a kill in an Arms Race or Demolition match
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_FIRST_KILL: boolean;

  /**
   * ### First Things First
   * Personally kill the entire Terrorist team before the bomb is planted in Demolition Mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_FIRST_THING_FIRST: boolean;

  /**
   * ### Target Secured
   * Personally kill the entire Counter-Terrorist team before the bomb is planted in Demolition Mode
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_TARGET_SECURED: boolean;

  /**
   * ### One Shot One Kill
   * Kill three consecutive players using the first bullet of your gun in Arms Race mode
   * - default value: `false`
   * - hidden: `false`
   */
  ONE_SHOT_ONE_KILL: boolean;

  /**
   * ### Conservationist
   * Win an Arms Race match without reloading any of your weapons
   * - default value: `false`
   * - hidden: `false`
   */
  GUN_GAME_CONSERVATIONIST: boolean;

  /**
   * ### Base Scamper
   * Kill an enemy just as their respawn protection ends in Arms Race mode
   * - default value: `false`
   * - hidden: `false`
   */
  BASE_SCAMPER: boolean;

  /**
   * ### Born Ready
   * Kill an enemy with the first bullet after your respawn protection ends in Arms Race mode
   * - default value: `false`
   * - hidden: `false`
   */
  BORN_READY: boolean;

  /**
   * ### Still Alive
   * Survive more than 30 seconds with less than ten health in Arms Race or Demolition mode
   * - default value: `false`
   * - hidden: `false`
   */
  STILL_ALIVE: boolean;

  /**
   * ### Awardist
   * Earn 100 achievements
   * - default value: `false`
   * - hidden: `false`
   */
  MEDALIST: boolean;

  /**
   * ### Bank On It
   * Win five matches on Bank
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_BANK: boolean;

  /**
   * ### Baggage Claimer
   * Win five matches in Arms Race Mode on Baggage
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_AR_BAGGAGE: boolean;

  /**
   * ### PP-Bizon Expert
   * Kill 250 enemies with the PP-Bizon
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_BIZON: boolean;

  /**
   * ### Tec-9 Expert
   * Kill 100 enemies with the Tec-9
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_TEC9: boolean;

  /**
   * ### Zeus x27 Expert
   * Kill 10 enemies with the Zeus x27
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_TASER: boolean;

  /**
   * ### P2000/USP Tactical Expert
   * Kill 100 enemies with the P2000 or USP
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_HKP2000: boolean;

  /**
   * ### P250 Expert
   * Kill 25 enemies with the P250
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_P250: boolean;

  /**
   * ### SCAR-20 Expert
   * Kill 100 enemies with the SCAR-20
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SCAR20: boolean;

  /**
   * ### SG553 Expert
   * Kill 100 enemies with the SG553
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SG556: boolean;

  /**
   * ### SSG 08 Expert
   * Kill 100 enemies with the SSG 08
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SSG08: boolean;

  /**
   * ### MP7 Expert
   * Kill 250 enemies with the MP7
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MP7: boolean;

  /**
   * ### MP9 Expert
   * Kill 100 enemies with the MP9
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MP9: boolean;

  /**
   * ### MAG-7 Expert
   * Kill 50 enemies with the MAG-7
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MAG7: boolean;

  /**
   * ### Sawed-Off Expert
   * Kill 50 enemies with the Sawed-Off
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_SAWEDOFF: boolean;

  /**
   * ### Nova Expert
   * Kill 100 enemies with the Nova
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_NOVA: boolean;

  /**
   * ### Negev Expert
   * Kill 100 enemies with the Negev
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_NEGEV: boolean;

  /**
   * ### Flame Expert
   * Kill 100 enemies with the Molotov or Incendiary grenade
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_MOLOTOV: boolean;

  /**
   * ### Train Map Veteran
   * Win 100 rounds on Train
   * - default value: `false`
   * - hidden: `false`
   */
  WIN_MAP_DE_TRAIN: boolean;

  /**
   * ### Galil AR Expert
   * Kill 250 enemies with the Galil AR
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ENEMY_GALILAR: boolean;
}
