// This file is autogenerated by a script

export interface GTAVAdapter {
  stats: GTAVStats;
  achievements: GTAVAchievements;
}

interface GTAVStats {
  /**
   * ### Solid Gold, Baby! Progress
   * - default value: `0`
   */
  Stat_ACH10: number;

  /**
   * ### Career Criminal Progress
   * - default value: `0`
   */
  Stat_ACH11: number;

  /**
   * ### TP Industries Arms Race Progress
   * - default value: `0`
   */
  Stat_ACH13: number;

  /**
   * ### Multi-Disciplined Progress
   * - default value: `0`
   */
  Stat_ACH14: number;

  /**
   * ### From Beyond the Stars Progress
   * - default value: `0`
   */
  Stat_ACH15: number;

  /**
   * ### A Mystery, Solved Progress
   * - default value: `0`
   */
  Stat_ACH16: number;

  /**
   * ### Waste Management  Progress
   * - default value: `0`
   */
  Stat_ACH17: number;

  /**
   * ### Red Mist Progress
   * - default value: `0`
   */
  Stat_ACH18: number;

  /**
   * ### Show Off Progress
   * - default value: `0`
   */
  Stat_ACH19: number;

  /**
   * ### Kifflom! Progress
   * - default value: `0`
   */
  Stat_ACH20: number;

  /**
   * ### A Lot of Cheddar Progress
   * - default value: `0`
   */
  Stat_ACH24: number;

  /**
   * ### Close Shave Progress
   * - default value: `0`
   */
  Stat_ACH29: number;

  /**
   * ### Three-Bit Gangster Progress
   * - default value: `0`
   */
  Stat_ACH31: number;

  /**
   * ### Making Moves Progress
   * - default value: `0`
   */
  Stat_ACH32: number;

  /**
   * ### Above the Law Progress
   * - default value: `0`
   */
  Stat_ACH33: number;

  /**
   * ### The Midnight Club Progress
   * - default value: `0`
   */
  Stat_ACH35: number;

  /**
   * ### Unnatural Selection Progress
   * - default value: `0`
   */
  Stat_ACH36: number;

  /**
   * ### Decorated Progress
   * - default value: `0`
   */
  Stat_ACH41: number;

  /**
   * ### Stick Up Kid Progress
   * - default value: `0`
   */
  Stat_ACH43: number;

  /**
   * ### Live a Little Progress
   * - default value: `0`
   */
  Stat_ACHH7: number;

  /**
   * ### Mastermind Progress
   * - default value: `0`
   */
  Stat_ACHH10: number;

  /**
   * ### Majestic Progress
   * - default value: `0`
   */
  Stat_ACHR2: number;
}

interface GTAVAchievements {
  /**
   * ### Welcome to Los Santos
   * - default value: `false`
   * - hidden: `true`
   */
  ACH00: boolean;

  /**
   * ### A Friendship Resurrected
   * - default value: `false`
   * - hidden: `true`
   */
  ACH01: boolean;

  /**
   * ### A Fair Day's Pay
   * - default value: `false`
   * - hidden: `true`
   */
  ACH02: boolean;

  /**
   * ### The Moment of Truth
   * - default value: `false`
   * - hidden: `true`
   */
  ACH03: boolean;

  /**
   * ### To Live or Die in Los Santos
   * - default value: `false`
   * - hidden: `true`
   */
  ACH04: boolean;

  /**
   * ### Diamond Hard
   * - default value: `false`
   * - hidden: `true`
   */
  ACH05: boolean;

  /**
   * ### Subversive
   * - default value: `false`
   * - hidden: `true`
   */
  ACH06: boolean;

  /**
   * ### Blitzed
   * - default value: `false`
   * - hidden: `true`
   */
  ACH42: boolean;

  /**
   * ### Small Town, Big Job
   * - default value: `false`
   * - hidden: `true`
   */
  ACH07: boolean;

  /**
   * ### The Government Gimps
   * - default value: `false`
   * - hidden: `true`
   */
  ACH08: boolean;

  /**
   * ### The Big One!
   * - default value: `false`
   * - hidden: `true`
   */
  ACH09: boolean;

  /**
   * ### Solid Gold, Baby!
   * Earn 70 Gold Medals on Missions and Strangers and Freaks.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH10: boolean;

  /**
   * ### Career Criminal
   * Attain 100% Game Completion.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH11: boolean;

  /**
   * ### San Andreas Sightseer
   * Explore all of Los Santos and Blaine County.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH50: boolean;

  /**
   * ### All's Fare in Love and War
   * Purchase Downtown Cab Co. and complete a private fare.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH12: boolean;

  /**
   * ### TP Industries Arms Race
   * Purchase McKenzie Field Hangar and win the arms race.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH13: boolean;

  /**
   * ### Multi-Disciplined
   * Attain a gold medal in all applicable hobbies and pastimes.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH14: boolean;

  /**
   * ### From Beyond the Stars
   * Collect and return all spaceship parts.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH15: boolean;

  /**
   * ### A Mystery, Solved
   * Solve the mystery of Leonora Johnson.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH16: boolean;

  /**
   * ### Waste Management 
   * Purchase the old dock and collect all nuclear waste.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH17: boolean;

  /**
   * ### Red Mist
   * Complete all Rampages.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH18: boolean;

  /**
   * ### Show Off
   * Complete all Stunt Jumps. 
   * - default value: `false`
   * - hidden: `false`
   */
  ACH19: boolean;

  /**
   * ### Kifflom!
   * You completed the Epsilon program and achieved inner peace.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH20: boolean;

  /**
   * ### Three Man Army
   * Survive 3 minutes on at least a 3 star Wanted Level with all three characters together off mission.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH21: boolean;

  /**
   * ### Out of Your Depth
   * You're gonna need a bigger boat...
   * - default value: `false`
   * - hidden: `false`
   */
  ACH22: boolean;

  /**
   * ### Altruist Acolyte
   * Deliver an unsuspecting victim to the Altruist Cult.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH23: boolean;

  /**
   * ### A Lot of Cheddar
   * Spend a total of $200 million across all three characters.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH24: boolean;

  /**
   * ### Trading Pure Alpha
   * Make a profit over your total investments in the stock market.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH25: boolean;

  /**
   * ### Pimp My Sidearm
   * Fully mod a weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH26: boolean;

  /**
   * ### Wanted: Alive Or Alive
   * Deliver a bail bond target alive.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH27: boolean;

  /**
   * ### Los Santos Customs
   * Fully mod a vehicle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH28: boolean;

  /**
   * ### Close Shave
   * Complete all Under the Bridge and Knife Flight challenges.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH29: boolean;

  /**
   * ### Off the Plane
   * GTA Online: Complete the Introduction.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH30: boolean;

  /**
   * ### Three-Bit Gangster
   * GTA Online: Reach Rank 25.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH31: boolean;

  /**
   * ### Making Moves
   * GTA Online: Reach Rank 50.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH32: boolean;

  /**
   * ### Above the Law
   * GTA Online: Reach Rank 100.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH33: boolean;

  /**
   * ### Numero Uno
   * GTA Online: Obtain first place in all competitive game types.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH34: boolean;

  /**
   * ### The Midnight Club
   * GTA Online: Use custom vehicles to win 5 Races.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH35: boolean;

  /**
   * ### Unnatural Selection
   * GTA Online: Complete all 10 waves of a Survival.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH36: boolean;

  /**
   * ### Backseat Driver
   * GTA Online: Direct a driver to 1st place as co-driver in Rally Mode.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH38: boolean;

  /**
   * ### Run Like The Wind
   * GTA Online: Survive for a day with a Bounty on your head.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH39: boolean;

  /**
   * ### Clean Sweep
   * GTA Online: Finish a Gang Attack without dying and kill at least 10 enemies.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH40: boolean;

  /**
   * ### Decorated
   * GTA Online: Earn 30 Platinum Awards.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH41: boolean;

  /**
   * ### Stick Up Kid
   * GTA Online: Hold up all 20 Stores.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH43: boolean;

  /**
   * ### Enjoy Your Stay
   * GTA Online: Participate in everything Los Santos has to offer.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH45: boolean;

  /**
   * ### Crew Cut
   * GTA Online: Complete a Job as a member of a Crew.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH46: boolean;

  /**
   * ### Full Refund
   * GTA Online: Kill the thief that mugged you.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH47: boolean;

  /**
   * ### Dialling Digits
   * GTA Online: Call for a Backup Helicopter for the first time.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH48: boolean;

  /**
   * ### American Dream
   * GTA Online: Own an Apartment, Garage and an Insured Vehicle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH49: boolean;

  /**
   * ### A New Perspective
   * Play GTA V for 15 hours in first person mode.
   * - default value: `false`
   * - hidden: `false`
   */
  ACH51: boolean;

  /**
   * ### Be Prepared
   * - default value: `false`
   * - hidden: `true`
   */
  ACHH1: boolean;

  /**
   * ### In the Name of Science
   * - default value: `false`
   * - hidden: `true`
   */
  ACHH2: boolean;

  /**
   * ### Dead Presidents
   * - default value: `false`
   * - hidden: `true`
   */
  ACHH3: boolean;

  /**
   * ### Parole Day
   * - default value: `false`
   * - hidden: `true`
   */
  ACHH4: boolean;

  /**
   * ### Shot Caller
   * GTA Online: Invest your hard earned cash to set up a Heist.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH5: boolean;

  /**
   * ### Four Way
   * GTA Online: As Heist Leader set the Finale cut as 25% across all players.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH6: boolean;

  /**
   * ### Live a Little
   * GTA Online: Spend a total of $8,000,000 purchasing vehicles included as part of The Heists Update.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH7: boolean;

  /**
   * ### Can't Touch This
   * GTA Online: Complete a Heist Finale without taking any damage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH8: boolean;

  /**
   * ### Mastermind
   * GTA Online: Earn 25 platinum medals across Heist Setups and Finales.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH10: boolean;

  /**
   * ### Vinewood Visionary
   * Create and upload a video using the Rockstar Editor.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHH11: boolean;

  /**
   * ### Majestic
   * Create and export 10 videos using the Rockstar Editor.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR2: boolean;

  /**
   * ### Humans of Los Santos
   * Unlock all Special Characters and entered Director Mode as an actor from this category.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR3: boolean;

  /**
   * ### First Time Director
   * Enter Director Mode for the first time as an unlocked actor.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR4: boolean;

  /**
   * ### Animal Lover
   * Enter Director Mode as an unlocked animal actor for the first time.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR5: boolean;

  /**
   * ### Ensemble Piece
   * Unlock all Story Characters and enter Director Mode as an actor from this category.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR6: boolean;

  /**
   * ### Cult Movie
   * Enter Director Mode as Cris Formage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR7: boolean;

  /**
   * ### Location Scout
   * Visit all Locations in Director Mode.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR8: boolean;

  /**
   * ### Method Actor
   * Enter Director Mode using any of your own GTA Online characters.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHR9: boolean;

  /**
   * ### Cryptozoologist
   * - default value: `false`
   * - hidden: `true`
   */
  ACHR10: boolean;

  /**
   * ### Getting Started
   * GTA Online: You set up the Doomsday Heist.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHGO1: boolean;

  /**
   * ### The Data Breaches
   * - default value: `false`
   * - hidden: `true`
   */
  ACHGO2: boolean;

  /**
   * ### The Bogdan Problem
   * - default value: `false`
   * - hidden: `true`
   */
  ACHGO3: boolean;

  /**
   * ### The Doomsday Scenario
   * - default value: `false`
   * - hidden: `true`
   */
  ACHGO4: boolean;

  /**
   * ### A World Worth Saving
   * - default value: `false`
   * - hidden: `true`
   */
  ACHGO5: boolean;

  /**
   * ### Orbital Obliteration
   * GTA Online: You killed another player with the Orbital Cannon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHGO6: boolean;

  /**
   * ### Elitist
   * GTA Online: You completed all 3 Elite Challenges in The Doomsday Heist.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHGO7: boolean;

  /**
   * ### Masterminds
   * GTA Online: You completed all 3 Criminal Mastermind Challenges in The Doomsday Heist.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHGO8: boolean;
}
