// This file is autogenerated by a script

export interface Portal2Adapter {
  stats: Portal2Stats;
  achievements: Portal2Achievements;
}

interface Portal2Stats {
  /**
   * ### PS3_SP_progress
   * - default value: `0`
   */
  PS3_SP_progress: number;

  /**
   * ### PS3_bitfield_01_004
   * - default value: `0`
   */
  PS3_bitfield_01_004: number;

  /**
   * ### PS3_bitfield_01_008
   * - default value: `0`
   */
  PS3_bitfield_01_008: number;

  /**
   * ### PS3_bitfield_01_018
   * - default value: `0`
   */
  PS3_bitfield_01_018: number;

  /**
   * ### PS3_bitfield_01_020
   * - default value: `0`
   */
  PS3_bitfield_01_020: number;

  /**
   * ### PS3_bitfield_02_000
   * - default value: `0`
   */
  PS3_bitfield_02_000: number;

  /**
   * ### PS3_bitfield_02_004
   * - default value: `0`
   */
  PS3_bitfield_02_004: number;

  /**
   * ### PS3_bitfield_02_008
   * - default value: `0`
   */
  PS3_bitfield_02_008: number;

  /**
   * ### PS3_bitfield_02_00C
   * - default value: `0`
   */
  PS3_bitfield_02_00C: number;

  /**
   * ### PS3_bitfield_02_010
   * - default value: `0`
   */
  PS3_bitfield_02_010: number;

  /**
   * ### PS3_bitfield_03_03C
   * - default value: `0`
   */
  PS3_bitfield_03_03C: number;

  /**
   * ### PS3_bitfield_03_0A0
   * - default value: `0`
   */
  PS3_bitfield_03_0A0: number;

  /**
   * ### PS3_bitfield_03_104
   * - default value: `0`
   */
  PS3_bitfield_03_104: number;

  /**
   * ### PS3_bitfield_02_238
   * - default value: `0`
   */
  PS3_bitfield_02_238: number;

  /**
   * ### PS3_CFG_sys_version
   * - default value: `0`
   */
  PS3_CFG_sys_version: number;

  /**
   * ### PS3_CFG_sys_volume
   * - default value: `0`
   */
  PS3_CFG_sys_volume: number;

  /**
   * ### PS3_CFG_sys_snd_musicvolume
   * - default value: `0`
   */
  PS3_CFG_sys_snd_musicvolume: number;

  /**
   * ### PS3_CFG_sys_mat_monitorgamma
   * - default value: `0`
   */
  PS3_CFG_sys_mat_monitorgamma: number;

  /**
   * ### PS3_CFG_sys_cloud_saves
   * - default value: `0`
   */
  PS3_CFG_sys_cloud_saves: number;

  /**
   * ### PS3_CFG_sys_ss_splitmode
   * - default value: `0`
   */
  PS3_CFG_sys_ss_splitmode: number;

  /**
   * ### PS3_CFG_usr_version
   * - default value: `0`
   */
  PS3_CFG_usr_version: number;

  /**
   * ### PS3_CFG_usr_joy_pitchsensitivity
   * - default value: `0`
   */
  PS3_CFG_usr_joy_pitchsensitivity: number;

  /**
   * ### PS3_CFG_usr_joy_yawsensitivity
   * - default value: `0`
   */
  PS3_CFG_usr_joy_yawsensitivity: number;

  /**
   * ### PS3_CFG_usr_joy_cfg_preset
   * - default value: `0`
   */
  PS3_CFG_usr_joy_cfg_preset: number;

  /**
   * ### PS3_CFG_usr_joy_cfg_custom_bindingsA
   * - default value: `0`
   */
  PS3_CFG_usr_joy_cfg_custom_bindingsA: number;

  /**
   * ### PS3_CFG_usr_joy_cfg_custom_bindingsB
   * - default value: `0`
   */
  PS3_CFG_usr_joy_cfg_custom_bindingsB: number;

  /**
   * ### PS3_CFG_usrSS_version
   * - default value: `0`
   */
  PS3_CFG_usrSS_version: number;

  /**
   * ### PS3_CFG_usrSS_joy_pitchsensitivity
   * - default value: `0`
   */
  PS3_CFG_usrSS_joy_pitchsensitivity: number;

  /**
   * ### PS3_CFG_usrSS_joy_yawsensitivity
   * - default value: `0`
   */
  PS3_CFG_usrSS_joy_yawsensitivity: number;

  /**
   * ### PS3_CFG_usrSS_joy_cfg_preset
   * - default value: `0`
   */
  PS3_CFG_usrSS_joy_cfg_preset: number;

  /**
   * ### PS3_CFG_usrSS_joy_cfg_custom_bindingsA
   * - default value: `0`
   */
  PS3_CFG_usrSS_joy_cfg_custom_bindingsA: number;

  /**
   * ### PS3_CFG_usrSS_joy_cfg_custom_bindingsB
   * - default value: `0`
   */
  PS3_CFG_usrSS_joy_cfg_custom_bindingsB: number;

  /**
   * ### PS3_GI_lesson_version_number
   * - default value: `0`
   */
  PS3_GI_lesson_version_number: number;

  /**
   * ### PS3_GI_lesson_return_to_hub
   * - default value: `0`
   */
  PS3_GI_lesson_return_to_hub: number;

  /**
   * ### PS3_GI_lesson_create_left_portal
   * - default value: `0`
   */
  PS3_GI_lesson_create_left_portal: number;

  /**
   * ### PS3_GI_lesson_create_right_portal
   * - default value: `0`
   */
  PS3_GI_lesson_create_right_portal: number;

  /**
   * ### PS3_GI_lesson_movement
   * - default value: `0`
   */
  PS3_GI_lesson_movement: number;

  /**
   * ### PS3_GI_lesson_push_button
   * - default value: `0`
   */
  PS3_GI_lesson_push_button: number;

  /**
   * ### PS3_GI_lesson_countdown_timer
   * - default value: `0`
   */
  PS3_GI_lesson_countdown_timer: number;

  /**
   * ### PS3_GI_lesson_air_taunt
   * - default value: `0`
   */
  PS3_GI_lesson_air_taunt: number;

  /**
   * ### PS3_GI_lesson_new_taunt_earned
   * - default value: `0`
   */
  PS3_GI_lesson_new_taunt_earned: number;

  /**
   * ### PS3_GI_lesson_teach_auto_bounce_suppression
   * - default value: `0`
   */
  PS3_GI_lesson_teach_auto_bounce_suppression: number;

  /**
   * ### PS3_GI_lesson_zoom
   * - default value: `0`
   */
  PS3_GI_lesson_zoom: number;

  /**
   * ### PS3_GI_lesson_unzoom
   * - default value: `0`
   */
  PS3_GI_lesson_unzoom: number;

  /**
   * ### PS3_GI_lesson_jump
   * - default value: `0`
   */
  PS3_GI_lesson_jump: number;

  /**
   * ### PS3_GI_lesson_movement_sp
   * - default value: `0`
   */
  PS3_GI_lesson_movement_sp: number;

  /**
   * ### PS3_GI_lesson_drop_object
   * - default value: `0`
   */
  PS3_GI_lesson_drop_object: number;

  /**
   * ### PS3_GI_lesson_pick_up_object
   * - default value: `0`
   */
  PS3_GI_lesson_pick_up_object: number;

  /**
   * ### PS3_GI_lesson_partner_view
   * - default value: `0`
   */
  PS3_GI_lesson_partner_view: number;

  /**
   * ### PS3_GI_lesson_serverside_hint
   * - default value: `0`
   */
  PS3_GI_lesson_serverside_hint: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_1__0
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_1__0: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_1__1
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_1__1: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_2__0
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_2__0: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_2__1
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_2__1: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_3__0
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_3__0: number;

  /**
   * ### PS3_ACH_SPREAD_THE_LOVE_3__1
   * - default value: `0`
   */
  PS3_ACH_SPREAD_THE_LOVE_3__1: number;

  /**
   * ### PS3_ACH_SPEED_RUN_COOP_1_
   * - default value: `0`
   */
  PS3_ACH_SPEED_RUN_COOP_1_: number;

  /**
   * ### PS3_ACH_SPEED_RUN_COOP_2_
   * - default value: `0`
   */
  PS3_ACH_SPEED_RUN_COOP_2_: number;

  /**
   * ### PS3_ACH_SPEED_RUN_COOP_3_
   * - default value: `0`
   */
  PS3_ACH_SPEED_RUN_COOP_3_: number;

  /**
   * ### PS3_GAME_stat_player_steps
   * - default value: `0`
   */
  PS3_GAME_stat_player_steps: number;

  /**
   * ### PS3_GAME_stat_portals_placed
   * - default value: `0`
   */
  PS3_GAME_stat_portals_placed: number;

  /**
   * ### PS3_GAME_stat_portals_traveled
   * - default value: `0`
   */
  PS3_GAME_stat_portals_traveled: number;

  /**
   * ### SP_progress
   * - default value: `0`
   */
  SP_progress: number;

  /**
   * ### bitfield_01_004
   * - default value: `0`
   */
  bitfield_01_004: number;

  /**
   * ### bitfield_01_008
   * - default value: `0`
   */
  bitfield_01_008: number;

  /**
   * ### bitfield_01_018
   * - default value: `0`
   */
  bitfield_01_018: number;

  /**
   * ### bitfield_01_020
   * - default value: `0`
   */
  bitfield_01_020: number;

  /**
   * ### bitfield_02_000
   * - default value: `0`
   */
  bitfield_02_000: number;

  /**
   * ### bitfield_02_004
   * - default value: `0`
   */
  bitfield_02_004: number;

  /**
   * ### bitfield_02_008
   * - default value: `0`
   */
  bitfield_02_008: number;

  /**
   * ### bitfield_02_00C
   * - default value: `0`
   */
  bitfield_02_00C: number;

  /**
   * ### bitfield_02_010
   * - default value: `0`
   */
  bitfield_02_010: number;

  /**
   * ### GI_lesson_version_number
   * - default value: `0`
   */
  GI_lesson_version_number: number;

  /**
   * ### GI_lesson_return_to_hub
   * - default value: `0`
   */
  GI_lesson_return_to_hub: number;

  /**
   * ### GI_lesson_create_left_portal
   * - default value: `0`
   */
  GI_lesson_create_left_portal: number;

  /**
   * ### GI_lesson_create_right_portal
   * - default value: `0`
   */
  GI_lesson_create_right_portal: number;

  /**
   * ### GI_lesson_movement
   * - default value: `0`
   */
  GI_lesson_movement: number;

  /**
   * ### GI_lesson_push_button
   * - default value: `0`
   */
  GI_lesson_push_button: number;

  /**
   * ### GI_lesson_countdown_timer
   * - default value: `0`
   */
  GI_lesson_countdown_timer: number;

  /**
   * ### GI_lesson_air_taunt
   * - default value: `0`
   */
  GI_lesson_air_taunt: number;

  /**
   * ### GI_lesson_new_taunt_earned
   * - default value: `0`
   */
  GI_lesson_new_taunt_earned: number;

  /**
   * ### GI_lesson_teach_auto_bounce_suppression
   * - default value: `0`
   */
  GI_lesson_teach_auto_bounce_suppression: number;

  /**
   * ### GI_lesson_zoom
   * - default value: `0`
   */
  GI_lesson_zoom: number;

  /**
   * ### GI_lesson_unzoom
   * - default value: `0`
   */
  GI_lesson_unzoom: number;

  /**
   * ### GI_lesson_jump
   * - default value: `0`
   */
  GI_lesson_jump: number;

  /**
   * ### GI_lesson_movement_sp
   * - default value: `0`
   */
  GI_lesson_movement_sp: number;

  /**
   * ### GI_lesson_drop_object
   * - default value: `0`
   */
  GI_lesson_drop_object: number;

  /**
   * ### GI_lesson_pick_up_object
   * - default value: `0`
   */
  GI_lesson_pick_up_object: number;

  /**
   * ### GI_lesson_partner_view
   * - default value: `0`
   */
  GI_lesson_partner_view: number;

  /**
   * ### GI_lesson_serverside_hint
   * - default value: `0`
   */
  GI_lesson_serverside_hint: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_1__0
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_1__0: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_1__1
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_1__1: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_2__0
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_2__0: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_2__1
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_2__1: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_3__0
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_3__0: number;

  /**
   * ### ACH_SPREAD_THE_LOVE_3__1
   * - default value: `0`
   */
  ACH_SPREAD_THE_LOVE_3__1: number;

  /**
   * ### ACH_SPEED_RUN_COOP_1_
   * - default value: `0`
   */
  ACH_SPEED_RUN_COOP_1_: number;

  /**
   * ### ACH_SPEED_RUN_COOP_2_
   * - default value: `0`
   */
  ACH_SPEED_RUN_COOP_2_: number;

  /**
   * ### ACH_SPEED_RUN_COOP_3_
   * - default value: `0`
   */
  ACH_SPEED_RUN_COOP_3_: number;

  /**
   * ### GAME_stat_player_steps
   * - default value: `0`
   */
  GAME_stat_player_steps: number;

  /**
   * ### GAME_stat_portals_placed
   * - default value: `0`
   */
  GAME_stat_portals_placed: number;

  /**
   * ### GAME_stat_portals_traveled
   * - default value: `0`
   */
  GAME_stat_portals_traveled: number;

  /**
   * ### PS3_CFG_usr_sixense_sensitivity_level
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_sensitivity_level: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_heading_multiplier
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_heading_multiplier: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_pitch_multiplier
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_pitch_multiplier: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_accel_band_exponent
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_accel_band_exponent: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_accel_band_size
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_accel_band_size: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_max_speed
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_max_speed: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_dead_zone_radius
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_dead_zone_radius: number;

  /**
   * ### PS3_CFG_usr_sixense_aim_freeaim_pitch_offset
   * - default value: `0`
   */
  PS3_CFG_usr_sixense_aim_freeaim_pitch_offset: number;

  /**
   * ### PS3_CFG_usrSS_sixense_sensitivity_level
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_sensitivity_level: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_heading_multiplier
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_heading_multiplier: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_pitch_multiplier
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_pitch_multiplier: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_accel_band_exponent
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_accel_band_exponent: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_accel_band_size
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_accel_band_size: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_max_speed
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_max_speed: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_dead_zone_radius
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_dead_zone_radius: number;

  /**
   * ### PS3_CFG_usrSS_sixense_aim_freeaim_pitch_offset
   * - default value: `0`
   */
  PS3_CFG_usrSS_sixense_aim_freeaim_pitch_offset: number;
}

interface Portal2Achievements {
  /**
   * ### Wake Up Call
   * Survive the manual override
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SURVIVE_CONTAINER_RIDE: boolean;

  /**
   * ### You Monster
   * Reunite with GLaDOS
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_WAKE_UP: boolean;

  /**
   * ### Undiscouraged
   * Complete the first Thermal Discouragement Beam test
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_LASER: boolean;

  /**
   * ### Bridge Over Troubling Water
   * Complete the first Hard Light Bridge test
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_BRIDGE: boolean;

  /**
   * ### SaBOTour
   * Make a break for it
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_BREAK_OUT: boolean;

  /**
   * ### Stalemate Associate
   * Press the button!
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_STALEMATE_ASSOCIATE: boolean;

  /**
   * ### Tater Tote
   * Carry science forward
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_ADDICTED_TO_SPUDS: boolean;

  /**
   * ### Vertically Unchallenged
   * Master the Repulsion Gel
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_BLUE_GEL: boolean;

  /**
   * ### Stranger Than Friction
   * Master the Propulsion Gel
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_ORANGE_GEL: boolean;

  /**
   * ### White Out
   * Complete the first Conversion Gel test
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_WHITE_GEL: boolean;

  /**
   * ### Tunnel of Funnel
   * Master the Excursion Funnel
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TRACTOR_BEAM: boolean;

  /**
   * ### Dual Pit Experiment
   * Do the same test twice
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TRIVIAL_TEST: boolean;

  /**
   * ### The Part Where He Kills You
   * This is that part
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_WHEATLEY_TRIES_TO: boolean;

  /**
   * ### Lunacy
   * That just happened
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SHOOT_THE_MOON: boolean;

  /**
   * ### Drop Box
   * Place a cube on a button without touching the cube
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_BOX_HOLE_IN_ONE: boolean;

  /**
   * ### Overclocker
   * Complete Test Chamber 10 in 70 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SPEED_RUN_LEVEL: boolean;

  /**
   * ### Pit Boss
   * Show that pit who's boss
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_COMPLIANT: boolean;

  /**
   * ### Preservation of Mass
   * Break the rules in Test Chamber 07
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SAVE_CUBE: boolean;

  /**
   * ### Pturretdactyl
   * Use an Aerial Faith Plate to launch a turret
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_LAUNCH_TURRET: boolean;

  /**
   * ### Final Transmission
   * Find the hidden signal in one of the Rat Man's dens
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_CLEAN_UP: boolean;

  /**
   * ### Good Listener
   * Take GLaDOS' escape advice
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_REENTER_TEST_CHAMBERS: boolean;

  /**
   * ### Scanned Alone
   * Stand in a defective turret detector
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_NOT_THE_DROID: boolean;

  /**
   * ### No Hard Feelings
   * Save a turret from redemption
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SAVE_REDEMPTION_TURRET: boolean;

  /**
   * ### Schrodinger's Catch
   * Catch a blue-painted box before it touches the ground
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_CATCH_CRAZY_BOX: boolean;

  /**
   * ### Ship Overboard
   * Discover the missing experiment
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_NO_BOAT: boolean;

  /**
   * ### Door Prize
   * Examine all the vitrified test chamber doors
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_A3_DOORS: boolean;

  /**
   * ### Portrait of a Lady
   * Find a hidden portrait
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_PORTRAIT: boolean;

  /**
   * ### You Made Your Point
   * Refuse to solve the first test in Chapter 8
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_DEFIANT: boolean;

  /**
   * ### Smash TV
   * Break 11 test chamber monitors
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_BREAK_MONITORS: boolean;

  /**
   * ### High Five
   * Celebrate your cooperative calibration success
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_HI_FIVE_YOUR_PARTNER: boolean;

  /**
   * ### Team Building
   * Complete all test chambers in the Team Building co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TEAM_BUILDING: boolean;

  /**
   * ### Confidence Building
   * Complete all test chambers in the Mass and Velocity co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_MASS_AND_VELOCITY: boolean;

  /**
   * ### Bridge Building
   * Complete all test chambers in the Hard-Light Surfaces co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_HUG_NAME: boolean;

  /**
   * ### Obstacle Building
   * Complete all test chambers in the Excursion Funnels co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_EXCURSION_FUNNELS: boolean;

  /**
   * ### You Saved Science
   * Complete all test chambers in all courses of co-op
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_NEW_BLOOD: boolean;

  /**
   * ### Iron Grip
   * Never lose a cube in Chamber 6 of the Mass and Velocity co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_NICE_CATCH: boolean;

  /**
   * ### Gesticul-8
   * Perform all 8 gestures of your own volition in co-op
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TAUNTS: boolean;

  /**
   * ### Can't Touch This
   * Dance in front of a turret blocked by a hard light bridge in co-op
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_YOU_MONSTER: boolean;

  /**
   * ### Empty Gesture
   * Drop your co-op partner in goo while they are gesturing by removing the bridge under them
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_PARTNER_DROP: boolean;

  /**
   * ### Party of Three
   * Find the hidden companion cube in co-op test chamber
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_PARTY_OF_THREE: boolean;

  /**
   * ### Narbacular Drop
   * Place a portal under your co-op partner while they are gesturing
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_PORTAL_TAUNT: boolean;

  /**
   * ### Professor Portal
   * After completing co-op, complete Calibration Course online with a friend who hasn’t played before
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TEACHER: boolean;

  /**
   * ### Air Show
   * Perform 2 aerial gestures before touching the ground in co-op
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_WITH_STYLE: boolean;

  /**
   * ### Portal Conservation Society
   * Complete Chamber 3 in the Hard-Light Surfaces co-op course using only 5 total portal placements
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_LIMITED_PORTALS: boolean;

  /**
   * ### Four Ring Circus
   * Enter 4 different portals without touching the ground in co-op
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_FOUR_PORTALS: boolean;

  /**
   * ### Triple Crown
   * Solve 3 co-op chambers in the Mass and Velocity course in under 60 seconds each
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SPEED_RUN_COOP: boolean;

  /**
   * ### Still Alive
   * Complete Course 4 with neither you nor your co-op partner dying
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_STAYING_ALIVE: boolean;

  /**
   * ### Asking for Trouble
   * Taunt GLaDOS in front of a camera in each of the five co-op courses
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_TAUNT_CAMERA: boolean;

  /**
   * ### Rock Portal Scissors
   * Win 3 co-op games of rock-paper-scissors in a row
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_ROCK_CRUSHES_ROBOT: boolean;

  /**
   * ### Friends List With Benefits
   * While playing co-op, hug 3 different people on your friends list
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SPREAD_THE_LOVE: boolean;

  /**
   * ### Talent Show
   * Never lose a cube in Chamber 6 of the Mobility Gels co-op course
   * - default value: `false`
   * - hidden: `false`
   */
  ACH_SUMMER_SALE: boolean;
}
