// This file is autogenerated by a script

export interface RustAdapter {
  stats: RustStats;
  achievements: RustAchievements;
}

interface RustStats {
  /**
   * ### Deaths
   * - default value: `0`
   */
  deaths: number;

  /**
   * ### Projectiles Fired
   * - default value: `0`
   */
  projectile_fired: number;

  /**
   * ### Bullets Fired
   * - default value: `0`
   */
  bullet_fired: number;

  /**
   * ### Arrows Fired
   * - default value: `0`
   */
  arrow_fired: number;

  /**
   * ### Rockets Fired
   * - default value: `0`
   */
  rocket_fired: number;

  /**
   * ### Headshots
   * - default value: `0`
   */
  headshots: number;

  /**
   * ### Items Dropped
   * - default value: `0`
   */
  item_drop: number;

  /**
   * ### Blueprints Studied
   * - default value: `0`
   */
  blueprint_studied: number;

  /**
   * ### Suicides
   * - default value: `0`
   */
  death_suicide: number;

  /**
   * ### Fall
   * - default value: `0`
   */
  death_fall: number;

  /**
   * ### Killed self in unknown way
   * - default value: `0`
   */
  death_selfinflicted: number;

  /**
   * ### Murders
   * - default value: `0`
   */
  kill_player: number;

  /**
   * ### Bullets fired that hit a player
   * - default value: `0`
   */
  bullet_hit_player: number;

  /**
   * ### Arrows that hit an unknown entity
   * - default value: `0`
   */
  arrow_hit_entity: number;

  /**
   * ### Harvested animal fat
   * - default value: `0`
   */
  harvest_fat_animal: number;

  /**
   * ### Harvested Stones
   * - default value: `0`
   */
  harvest_stones: number;

  /**
   * ### Bullets that hit an unkown entity
   * - default value: `0`
   */
  bullet_hit_entity: number;

  /**
   * ### Harvested cloth
   * - default value: `0`
   */
  harvest_cloth: number;

  /**
   * ### Harvested Wood
   * - default value: `0`
   */
  harvest_wood: number;

  /**
   * ### Arrows that hit a building
   * - default value: `0`
   */
  arrow_hit_building: number;

  /**
   * ### kill_bear
   * - default value: `0`
   */
  kill_bear: number;

  /**
   * ### kill_boar
   * - default value: `0`
   */
  kill_boar: number;

  /**
   * ### kill_stag
   * - default value: `0`
   */
  kill_stag: number;

  /**
   * ### kill_chicken
   * - default value: `0`
   */
  kill_chicken: number;

  /**
   * ### kill_horse
   * - default value: `0`
   */
  kill_horse: number;

  /**
   * ### kill_wolf
   * - default value: `0`
   */
  kill_wolf: number;

  /**
   * ### harvest_metal_ore
   * - default value: `0`
   */
  harvest_metal_ore: number;

  /**
   * ### headshot
   * - default value: `0`
   */
  headshot: number;

  /**
   * ### harvest_sulfur_ore
   * - default value: `0`
   */
  harvest_sulfur_ore: number;

  /**
   * ### harvest_bone_fragments
   * - default value: `0`
   */
  harvest_bone_fragments: number;

  /**
   * ### harvest_humanmeat_raw
   * - default value: `0`
   */
  harvest_humanmeat_raw: number;

  /**
   * ### arrow_hit_boar
   * - default value: `0`
   */
  arrow_hit_boar: number;

  /**
   * ### arrow_hit_bear
   * - default value: `0`
   */
  arrow_hit_bear: number;

  /**
   * ### arrow_hit_wolf
   * - default value: `0`
   */
  arrow_hit_wolf: number;

  /**
   * ### arrow_hit_stag
   * - default value: `0`
   */
  arrow_hit_stag: number;

  /**
   * ### arrow_hit_chicken
   * - default value: `0`
   */
  arrow_hit_chicken: number;

  /**
   * ### bullet_hit_building
   * - default value: `0`
   */
  bullet_hit_building: number;

  /**
   * ### harvest_wolfmeat_raw
   * - default value: `0`
   */
  harvest_wolfmeat_raw: number;

  /**
   * ### harvest_skull_human
   * - default value: `0`
   */
  harvest_skull_human: number;

  /**
   * ### harvest_skull_wolf
   * - default value: `0`
   */
  harvest_skull_wolf: number;

  /**
   * ### arrow_hit_horse
   * - default value: `0`
   */
  arrow_hit_horse: number;

  /**
   * ### arrow_hit_player
   * - default value: `0`
   */
  arrow_hit_player: number;

  /**
   * ### death_entity
   * - default value: `0`
   */
  death_entity: number;

  /**
   * ### death_wolf
   * - default value: `0`
   */
  death_wolf: number;

  /**
   * ### death_bear
   * - default value: `0`
   */
  death_bear: number;

  /**
   * ### shotgun_fired
   * - default value: `0`
   */
  shotgun_fired: number;

  /**
   * ### shotgun_hit_building
   * - default value: `0`
   */
  shotgun_hit_building: number;

  /**
   * ### shotgun_hit_player
   * - default value: `0`
   */
  shotgun_hit_player: number;

  /**
   * ### shotgun_hit_horse
   * - default value: `0`
   */
  shotgun_hit_horse: number;

  /**
   * ### bullet_hit_bear
   * - default value: `0`
   */
  bullet_hit_bear: number;

  /**
   * ### shotgun_hit_entity
   * - default value: `0`
   */
  shotgun_hit_entity: number;

  /**
   * ### bullet_hit_horse
   * - default value: `0`
   */
  bullet_hit_horse: number;

  /**
   * ### bullet_hit_stag
   * - default value: `0`
   */
  bullet_hit_stag: number;

  /**
   * ### bullet_hit_wolf
   * - default value: `0`
   */
  bullet_hit_wolf: number;

  /**
   * ### bullet_hit_boar
   * - default value: `0`
   */
  bullet_hit_boar: number;

  /**
   * ### bullet_hit_sign
   * - default value: `0`
   */
  bullet_hit_sign: number;

  /**
   * ### wounded
   * - default value: `0`
   */
  wounded: number;

  /**
   * ### wounded_assisted
   * - default value: `0`
   */
  wounded_assisted: number;

  /**
   * ### wounded_healed
   * - default value: `0`
   */
  wounded_healed: number;

  /**
   * ### bullet_hit_playercorpse
   * - default value: `0`
   */
  bullet_hit_playercorpse: number;

  /**
   * ### bullet_hit_corpse
   * - default value: `0`
   */
  bullet_hit_corpse: number;

  /**
   * ### INVENTORY_OPENED
   * - default value: `0`
   */
  INVENTORY_OPENED: number;

  /**
   * ### CRAFTING_OPENED
   * - default value: `0`
   */
  CRAFTING_OPENED: number;

  /**
   * ### harvested_wood
   * - default value: `0`
   */
  harvested_wood: number;

  /**
   * ### harvested_stones
   * - default value: `0`
   */
  harvested_stones: number;

  /**
   * ### MAP_OPENED
   * - default value: `0`
   */
  MAP_OPENED: number;

  /**
   * ### CUPBOARD_OPENED
   * - default value: `0`
   */
  CUPBOARD_OPENED: number;

  /**
   * ### ITEM_EXAMINED
   * - default value: `0`
   */
  ITEM_EXAMINED: number;

  /**
   * ### ORE_HIT
   * - default value: `0`
   */
  ORE_HIT: number;

  /**
   * ### TREE_HIT
   * - default value: `0`
   */
  TREE_HIT: number;

  /**
   * ### comfort_duration
   * - default value: `0`
   */
  comfort_duration: number;

  /**
   * ### calories_consumed
   * - default value: `0`
   */
  calories_consumed: number;

  /**
   * ### water_consumed
   * - default value: `0`
   */
  water_consumed: number;

  /**
   * ### pickup_category_food_Old
   * - default value: `0`
   */
  pickup_category_food_Old: number;

  /**
   * ### pickup_category_food
   * - default value: `0`
   */
  pickup_category_food: number;

  /**
   * ### radiation_exposure_duration
   * - default value: `0`
   */
  radiation_exposure_duration: number;

  /**
   * ### cold_exposure_duration
   * - default value: `0`
   */
  cold_exposure_duration: number;

  /**
   * ### hot_exposure_duration
   * - default value: `0`
   */
  hot_exposure_duration: number;

  /**
   * ### melee_strikes
   * - default value: `0`
   */
  melee_strikes: number;

  /**
   * ### melee_thrown
   * - default value: `0`
   */
  melee_thrown: number;

  /**
   * ### placed_blocks
   * - default value: `0`
   */
  placed_blocks: number;

  /**
   * ### upgraded_blocks
   * - default value: `0`
   */
  upgraded_blocks: number;

  /**
   * ### arrows_shot
   * - default value: `0`
   */
  arrows_shot: number;

  /**
   * ### seconds_speaking
   * - default value: `0`
   */
  seconds_speaking: number;

  /**
   * ### harvested_cloth
   * - default value: `0`
   */
  harvested_cloth: number;

  /**
   * ### harvested_leather
   * - default value: `0`
   */
  harvested_leather: number;

  /**
   * ### acquired_lowgradefuel
   * - default value: `0`
   */
  acquired_lowgradefuel: number;

  /**
   * ### acquired_metal_ore
   * - default value: `0`
   */
  acquired_metal_ore: number;

  /**
   * ### acquired_scrap
   * - default value: `0`
   */
  acquired_scrap: number;

  /**
   * ### topology_road_duration
   * - default value: `0`
   */
  topology_road_duration: number;

  /**
   * ### destroyed_barrels
   * - default value: `0`
   */
  destroyed_barrels: number;

  /**
   * ### horse_distance_ridden
   * - default value: `0`
   */
  horse_distance_ridden: number;

  /**
   * ### helipad_landings
   * - default value: `0`
   */
  helipad_landings: number;

  /**
   * ### cargoship_bridge_visits
   * - default value: `0`
   */
  cargoship_bridge_visits: number;

  /**
   * ### recycled_cans
   * - default value: `0`
   */
  recycled_cans: number;

  /**
   * ### kill_scientist
   * - default value: `0`
   */
  kill_scientist: number;

  /**
   * ### horse_distance_ridden_km
   * - default value: `0`
   */
  horse_distance_ridden_km: number;

  /**
   * ### notesplayed_bass
   * - default value: `0`
   */
  notesplayed_bass: number;

  /**
   * ### notesplayed_cowbell
   * - default value: `0`
   */
  notesplayed_cowbell: number;

  /**
   * ### notesplayed_drumkit
   * - default value: `0`
   */
  notesplayed_drumkit: number;

  /**
   * ### notesplayed_flute
   * - default value: `0`
   */
  notesplayed_flute: number;

  /**
   * ### notesplayed_acousticguitar
   * - default value: `0`
   */
  notesplayed_acousticguitar: number;

  /**
   * ### notesplayed_jerrycanguitar
   * - default value: `0`
   */
  notesplayed_jerrycanguitar: number;

  /**
   * ### notesplayed_piano
   * - default value: `0`
   */
  notesplayed_piano: number;

  /**
   * ### notesplayed_tambourine
   * - default value: `0`
   */
  notesplayed_tambourine: number;

  /**
   * ### notesplayed_trumpet
   * - default value: `0`
   */
  notesplayed_trumpet: number;

  /**
   * ### notesplayed_tuba
   * - default value: `0`
   */
  notesplayed_tuba: number;

  /**
   * ### notesplayed_xylophone
   * - default value: `0`
   */
  notesplayed_xylophone: number;

  /**
   * ### notesplayed
   * - default value: `0`
   */
  notesplayed: number;

  /**
   * ### InstrumentNotesPlayed
   * - default value: `0`
   */
  InstrumentNotesPlayed: number;

  /**
   * ### InstrumentFullKeyboardMode
   * - default value: `0`
   */
  InstrumentFullKeyboardMode: number;

  /**
   * ### InstrumentNotesPlayedBinds
   * - default value: `0`
   */
  InstrumentNotesPlayedBinds: number;

  /**
   * ### grenades_thrown
   * - default value: `0`
   */
  grenades_thrown: number;

  /**
   * ### gesture_wave_count
   * - default value: `0`
   */
  gesture_wave_count: number;
}

interface RustAchievements {
  /**
   * ### Place Camp Fire
   * Place a camp fire
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_CAMPFIRE: boolean;

  /**
   * ### Craft Camp Fire
   * Craft a campfire
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_CAMPFIRE: boolean;

  /**
   * ### Collect Wood
   * Collect 100 Wood
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_100_WOOD: boolean;

  /**
   * ### Craft Stone Hatchet
   * 
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_STONE_HATCHET: boolean;

  /**
   * ### Collect 200 Stone
   * 
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_200_STONE: boolean;

  /**
   * ### Craft Stone Pickaxe
   * 
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_STONE_PICKAXE: boolean;

  /**
   * ### Place Sleeping Bag
   * Place a sleeping bag
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_SLEEPINGBAG: boolean;

  /**
   * ### Collect 700 Wood
   * Collect 700 Wood
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_700_WOOD: boolean;

  /**
   * ### Craft Spear
   * Craft a wooden spear
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_SPEAR: boolean;

  /**
   * ### Craft Sleeping Bag
   * Craft a Sleeping Bag
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_SLEEPINGBAG: boolean;

  /**
   * ### Collect 30 Cloth
   * Collect 30 Cloth
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_30_CLOTH: boolean;

  /**
   * ### Craft Building Plan
   * Craft a Building Plan
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_BUILDING_PLAN: boolean;

  /**
   * ### Craft Hammer
   * Craft a Hammer
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_HAMMER: boolean;

  /**
   * ### Construct Base
   * Construct a Base
   * - default value: `false`
   * - hidden: `false`
   */
  CONSTRUCT_BASE: boolean;

  /**
   * ### Upgrade Base
   * Upgrade your base
   * - default value: `false`
   * - hidden: `false`
   */
  UPGRADE_BASE: boolean;

  /**
   * ### Craft Wooden Door
   * Craft a Wooden Door
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_WOODEN_DOOR: boolean;

  /**
   * ### Craft Lock
   * Craft a lock
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_LOCK: boolean;

  /**
   * ### Place Wooden Door
   * Place a Wooden Door
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_WOODEN_DOOR: boolean;

  /**
   * ### Place Lock
   * Place a Lock
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_LOCK: boolean;

  /**
   * ### Lock the Lock
   * Lock the Lock
   * - default value: `false`
   * - hidden: `false`
   */
  LOCK_LOCK: boolean;

  /**
   * ### Craft Tool Cupboard
   * Craft a Tool Cupboard
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_TOOL_CUPBOARD: boolean;

  /**
   * ### Place Tool Cupboard
   * Place a tool Cupboard
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_TOOL_CUPBOARD: boolean;

  /**
   * ### Collect 50 Cloth
   * Collect 50 Cloth
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_50_CLOTH: boolean;

  /**
   * ### Craft Hunting Bow
   * Craft a Hunting Bow
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_HUNTING_BOW: boolean;

  /**
   * ### Craft Arrows
   * Craft some Arrows
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_ARROWS: boolean;

  /**
   * ### Kill an Animal
   * Kill an Animal
   * - default value: `false`
   * - hidden: `false`
   */
  KILL_ANIMAL: boolean;

  /**
   * ### Skin an Animal
   * Skin an Animal
   * - default value: `false`
   * - hidden: `false`
   */
  SKIN_ANIMAL: boolean;

  /**
   * ### Craft Burlap Headwrap
   * Craft a Burlap Headwrap
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_BURLAP_HEADWRAP: boolean;

  /**
   * ### Craft Burlap Shirt
   * Craft a Burlap Shirt
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_BURLAP_SHIRT: boolean;

  /**
   * ### Craft Burlap Pants
   * Craft Burlap Pants
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_BURLAP_PANTS: boolean;

  /**
   * ### Equip Clothing
   * Equip 3 pieces of clothing
   * - default value: `false`
   * - hidden: `false`
   */
  EQUIP_CLOTHING: boolean;

  /**
   * ### Craft Wooden Box
   * Craft a Wooden Box
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_WOODEN_BOX: boolean;

  /**
   * ### Place Wooden Box
   * Place a Wooden Box
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_WOODEN_BOX: boolean;

  /**
   * ### Acquire 50 Low Grade Fuel
   * Acquire 50 Low Grade Fuel
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_50_LGF: boolean;

  /**
   * ### Craft a Furnace
   * Craft a Furnace
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_FURNACE: boolean;

  /**
   * ### Place a Furnace
   * Place a Furnace
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_FURNACE: boolean;

  /**
   * ### Collect 300 Metal Ore
   * Collect 300 Metal Ore
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_300_METAL_ORE: boolean;

  /**
   * ### Craft a Machete
   * Craft a Machete
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_MACHETE: boolean;

  /**
   * ### Visit a Road
   * Visit a Road
   * - default value: `false`
   * - hidden: `false`
   */
  VISIT_ROAD: boolean;

  /**
   * ### Collect 65 Scrap
   * Collect 65 Scrap
   * - default value: `false`
   * - hidden: `false`
   */
  COLLECT_65_SCRAP: boolean;

  /**
   * ### Destroy 10 Barrels
   * Destroy 10 Barrels
   * - default value: `false`
   * - hidden: `false`
   */
  DESTROY_10_BARRELS: boolean;

  /**
   * ### Craft a Workbench
   * Craft a Workbench
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_WORKBENCH: boolean;

  /**
   * ### Place a Workbench
   * Place a Workbench
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_WORKBENCH: boolean;

  /**
   * ### Craft a Nailgun
   * Craft a Nailgun
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_NAILGUN: boolean;

  /**
   * ### Craft Nailgun Nails
   * Craft Nailgun Nails
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_NAILGUN_NAILS: boolean;

  /**
   * ### Research an Item
   * Research an Item
   * - default value: `false`
   * - hidden: `false`
   */
  RESEARCH_ITEM: boolean;

  /**
   * ### Craft a Research Table
   * Craft a Research Table
   * - default value: `false`
   * - hidden: `false`
   */
  CRAFT_RESEARCH_TABLE: boolean;

  /**
   * ### Place a Research Table
   * Place a Research Table
   * - default value: `false`
   * - hidden: `false`
   */
  PLACE_RESEARCH_TABLE: boolean;

  /**
   * ### Glutton
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  GLUTTON: boolean;

  /**
   * ### Sealbreaker
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  SEALBREAKER: boolean;

  /**
   * ### Save The Planet
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  SAVE_THE_PLANET: boolean;

  /**
   * ### I'm the Captain now
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  IM_THE_CAPTAIN_NOW: boolean;

  /**
   * ### On The Deck
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  ON_THE_DECK: boolean;

  /**
   * ### Giddy Up!
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  GIDDY_UP: boolean;

  /**
   * ### Something of a scientist myself
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  KILL_SCIENTIST: boolean;

  /**
   * ### First Notes
   * Play your first instrument
   * - default value: `false`
   * - hidden: `false`
   */
  PLAY_INSTRUMENT: boolean;

  /**
   * ### Musical Maestro
   * Play every instrument
   * - default value: `false`
   * - hidden: `false`
   */
  PLAY_ALL_INSTRUMENTS: boolean;

  /**
   * ### Getting the band together
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  TEAM_INSTRUMENTS: boolean;

  /**
   * ### Cool Kids Club
   * Be in a team where every team member is riding a Boogie Board or Inner Tube (minimum 4 members)
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_INFLATABLE: boolean;

  /**
   * ### Paparazzi
   * Take a photo of another player
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_PAPARAZZI: boolean;

  /**
   * ### Sunglasses at Night
   * 
   * - default value: `false`
   * - hidden: `true`
   */
  SUMMER_SUNGLASSES: boolean;

  /**
   * ### Radical
   * Splash another player with a Water Pistol while that player is irradiated
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_RADICAL: boolean;

  /**
   * ### Soaked
   * Soak another player above the damage threshold using a water gun.
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_SOAKED: boolean;

  /**
   * ### Liquidator
   * Get a kill using a water gun.
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_LIQUIDATOR: boolean;

  /**
   * ### No Pressure
   * Get a kill with a super soaker pumped at the lowest pressure.
   * - default value: `false`
   * - hidden: `false`
   */
  SUMMER_NO_PRESSURE: boolean;

  /**
   * ### Party Boat
   * Dance with 2 other players at the front of the Cargo Ship.
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_PARTYBOAT: boolean;

  /**
   * ### Bad Neighbour
   * Use a megaphone while in another player's Tool Cupboard radius.
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_BADNEIGHBOUR: boolean;

  /**
   * ### On the Record
   * Record another player speaking onto a Cassette.
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_ONRECORD: boolean;

  /**
   * ### Like Nobody's Watching
   * Dance near a playing Boom Box on an active Disco Floor.
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_NOBODYSWATCHING: boolean;

  /**
   * ### I can no longer see
   * Stare into a laser light for 30 seconds.
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_NOLONGERSEE: boolean;

  /**
   * ### I should buy this Soundtrack
   * Listen to the Rust soundtrack from a Boom Box for 30 seconds
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_BUYSOUNDTRACK: boolean;

  /**
   * ### Full Collection
   * Play an instrument while floating in an Inner Tube while listening to a Boom Box play a radio stream
   * - default value: `false`
   * - hidden: `false`
   */
  VOICEPROPS_FULLCOLLECTION: boolean;
}
