// This file is autogenerated by a script

export interface WarframeAdapter {
  stats: WarframeStats;
  achievements: WarframeAchievements;
}

interface WarframeStats {
  /**
   * ### Ciphers Solved
   * - default value: `0`
   */
  CIPHER_SOLVED: number;

  /**
   * ### Credits Earned
   * - default value: `0`
   */
  INCOME: number;

  /**
   * ### Items Crafted
   * - default value: `0`
   */
  ITEM_CRAFTED: number;

  /**
   * ### Allies Revived
   * - default value: `0`
   */
  REVIVE_BUDDY: number;

  /**
   * ### Sold in Market
   * - default value: `0`
   */
  SELL_ITEM: number;

  /**
   * ### Mods Collected
   * - default value: `0`
   */
  UPGRADE_RECEIVED: number;

  /**
   * ### Mission Time
   * - default value: `0`
   */
  PLAY_TIME: number;
}

interface WarframeAchievements {
  /**
   * ### We Shape Our Tools
   * Apply a Mod to a weapon or Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_1: boolean;

  /**
   * ### Our Tools Shape Us
   * Apply 4 different Mods to a single weapon or Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_2: boolean;

  /**
   * ### Blade Mastery I
   * Reach Rank 10 with any five Longsword or Dual Short Blades weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_3: boolean;

  /**
   * ### Blade Mastery II
   * Reach Rank 20 with any five Longsword or Dual Short Blades weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_4: boolean;

  /**
   * ### Blade Mastery III
   * Reach Rank 30 with any five Longsword or Dual Short Blades weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_5: boolean;

  /**
   * ### Blade Proficiency I
   * Reach Rank 10 with any Longsword or Dual Short Blades weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_6: boolean;

  /**
   * ### Blade Proficiency II
   * Reach Rank 20 with any Longsword or Dual Short Blades weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_7: boolean;

  /**
   * ### Blade Proficiency III
   * Reach Rank 30 with any Longsword or Dual Short Blades weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_8: boolean;

  /**
   * ### Bow Mastery I
   * Reach Rank 10 with any two Bow weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_9: boolean;

  /**
   * ### Bow Mastery II
   * Reach Rank 20 with any two Bow weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_10: boolean;

  /**
   * ### Bow Mastery III
   * Reach Rank 30 with any two Bow weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_11: boolean;

  /**
   * ### Bow Proficiency I
   * Reach Rank 10 with any Bow weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_12: boolean;

  /**
   * ### Bow Proficiency II
   * Reach Rank 20 with any Bow weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_13: boolean;

  /**
   * ### Bow Proficiency III
   * Reach Rank 30 with any Bow weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_14: boolean;

  /**
   * ### Brawler Mastery I
   * Reach Rank 10 with any three Gauntlets or Hand-to-Hand weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_15: boolean;

  /**
   * ### Brawler Mastery II
   * Reach Rank 20 with any three Gauntlets or Hand-to-Hand weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_16: boolean;

  /**
   * ### Brawler Mastery III
   * Reach Rank 30 with any three Gauntlets or Hand-to-Hand weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_17: boolean;

  /**
   * ### Brawler Proficiency I
   * Reach Rank 10 with any Gauntlets or Hand-to-Hand weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_18: boolean;

  /**
   * ### Brawler Proficiency II
   * Reach Rank 20 with any Gauntlets or Hand-to-Hand weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_19: boolean;

  /**
   * ### Brawler Proficiency III
   * Reach Rank 30 with any Gauntlets or Hand-to-Hand weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_20: boolean;

  /**
   * ### Weaponsmith
   * Build an item in the Foundry.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_21: boolean;

  /**
   * ### Inventor
   * Build 10 items in the Foundry.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_22: boolean;

  /**
   * ### Scientist
   * Build 20 items in the Foundry.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_23: boolean;

  /**
   * ### Tailor Made
   * Customize the color of a Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_24: boolean;

  /**
   * ### Dagger Mastery I
   * Reach Rank 10 with any three Dagger or Dual Daggers weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_25: boolean;

  /**
   * ### Dagger Mastery II
   * Reach Rank 20 with any three Dagger or Dual Daggers weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_26: boolean;

  /**
   * ### Dagger Mastery III
   * Reach Rank 30 with any three Dagger or Dual Daggers weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_27: boolean;

  /**
   * ### Dagger Proficiency I
   * Reach Rank 10 with any Dagger or Dual Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_28: boolean;

  /**
   * ### Dagger Proficiency II
   * Reach Rank 20 with any Dagger or Dual Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_29: boolean;

  /**
   * ### Dagger Proficiency III
   * Reach Rank 30 with any Dagger or Dual Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_30: boolean;

  /**
   * ### Payday
   * Earn 1,000 Credits.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_31: boolean;

  /**
   * ### Nestegg
   * Earn 10,000 Credits.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_32: boolean;

  /**
   * ### Where Credit is Due
   * Earn 100,000 Credits.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_33: boolean;

  /**
   * ### Money is Power
   * Earn 1,000,000 Credits.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_34: boolean;

  /**
   * ### Secrets of the Orokin
   * Find 1 Mod.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_35: boolean;

  /**
   * ### Behold the Possibilities
   * Find 20 Mods.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_36: boolean;

  /**
   * ### Collector
   * Find 100 Mods.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_37: boolean;

  /**
   * ### So Many Choices
   * Find 1,000 Mods.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_38: boolean;

  /**
   * ### Greater Than the Sum
   * Fuse mods together to create a more powerful mod.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_39: boolean;

  /**
   * ### Heavy Weapon Mastery I
   * Reach Rank 10 with any two Heavy Axe, Heavy Hammer, or Heavy Sword weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_40: boolean;

  /**
   * ### Heavy Weapon Mastery II
   * Reach Rank 20 with any two Heavy Axe, Heavy Hammer, or Heavy Sword weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_41: boolean;

  /**
   * ### Heavy Weapon Mastery III
   * Reach Rank 30 with any two Heavy Axe, Heavy Hammer, or Heavy Sword weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_42: boolean;

  /**
   * ### Heavy Weapon Proficiency I
   * Reach Rank 10 with any Heavy Axe, Heavy Hammer, or Heavy Sword weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_43: boolean;

  /**
   * ### Heavy Weapon Proficiency II
   * Reach Rank 20 with any Heavy Axe, Heavy Hammer, or Heavy Sword weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_44: boolean;

  /**
   * ### Heavy Weapon Proficiency III
   * Reach Rank 30 with any Heavy Axe, Heavy Hammer, or Heavy Sword weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_45: boolean;

  /**
   * ### Angel of Death
   * Get 100 kills in a single mission.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_46: boolean;

  /**
   * ### A Watchful Eye
   * Obtain a Sentinel.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_47: boolean;

  /**
   * ### Building a Stable
   * Obtain 2 Warframes.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_48: boolean;

  /**
   * ### The Right Tool for the Job
   * Obtain 5 Warframes.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_49: boolean;

  /**
   * ### Each Tool with Its Own Purpose
   * Obtain 10 Warframes.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_50: boolean;

  /**
   * ### Pistol Mastery I
   * Reach Rank 10 with any five Pistol or Akimbo Pistols weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_51: boolean;

  /**
   * ### Pistol Mastery II
   * Reach Rank 20 with any five Pistol or Akimbo Pistols weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_52: boolean;

  /**
   * ### Pistol Mastery III
   * Reach Rank 30 with any five Pistol or Akimbo Pistols weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_53: boolean;

  /**
   * ### Pistol Proficiency I
   * Reach Rank 10 with any Pistol or Akimbo Pistols weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_54: boolean;

  /**
   * ### Pistol Proficiency II
   * Reach Rank 20 with any Pistol or Akimbo Pistols weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_55: boolean;

  /**
   * ### Pistol Proficiency III
   * Reach Rank 30 with any Pistol or Akimbo Pistols weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_56: boolean;

  /**
   * ### Hooked
   * Play for 2 hours.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_57: boolean;

  /**
   * ### It Keeps Getting Better
   * Play for 10 hours.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_58: boolean;

  /**
   * ### Pride of The Lotus
   * Play for 100 hours.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_59: boolean;

  /**
   * ### Initiate
   * Achieve the rank of Initiate.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_60: boolean;

  /**
   * ### Silver Initiate
   * Achieve the rank of Silver Initiate.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_61: boolean;

  /**
   * ### Gold Initiate
   * Achieve the rank of Gold Initiate.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_62: boolean;

  /**
   * ### Novice
   * Achieve the rank of Novice.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_63: boolean;

  /**
   * ### Silver Novice
   * Achieve the rank of Silver Novice.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_64: boolean;

  /**
   * ### Gold Novice
   * Achieve the rank of Gold Novice.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_65: boolean;

  /**
   * ### Disciple
   * Achieve the rank of Disciple.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_66: boolean;

  /**
   * ### Silver Disciple
   * Achieve the rank of Silver Disciple.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_67: boolean;

  /**
   * ### Gold Disciple
   * Achieve the rank of Gold Disciple.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_68: boolean;

  /**
   * ### Seeker
   * Achieve the rank of Seeker.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_69: boolean;

  /**
   * ### Silver Seeker
   * Achieve the rank of Silver Seeker.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_70: boolean;

  /**
   * ### Gold Seeker
   * Achieve the rank of Gold Seeker.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_71: boolean;

  /**
   * ### Hunter
   * Achieve the rank of Hunter.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_72: boolean;

  /**
   * ### Silver Hunter
   * Achieve the rank of Silver Hunter.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_73: boolean;

  /**
   * ### Gold Hunter
   * Achieve the rank of Gold Hunter.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_74: boolean;

  /**
   * ### Eagle
   * Achieve the rank of Eagle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_75: boolean;

  /**
   * ### Silver Eagle
   * Achieve the rank of Silver Eagle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_76: boolean;

  /**
   * ### Gold Eagle
   * Achieve the rank of Gold Eagle.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_77: boolean;

  /**
   * ### Tiger
   * Achieve the rank of Tiger.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_78: boolean;

  /**
   * ### Silver Tiger
   * Achieve the rank of Silver Tiger.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_79: boolean;

  /**
   * ### Gold Tiger
   * Achieve the rank of Gold Tiger.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_80: boolean;

  /**
   * ### Dragon
   * Achieve the rank of Dragon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_81: boolean;

  /**
   * ### Silver Dragon
   * Achieve the rank of Silver Dragon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_82: boolean;

  /**
   * ### Gold Dragon
   * Achieve the rank of Gold Dragon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_83: boolean;

  /**
   * ### Sage
   * Achieve the rank of Sage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_84: boolean;

  /**
   * ### Silver Sage
   * Achieve the rank of Silver Sage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_85: boolean;

  /**
   * ### Gold Sage
   * Achieve the rank of Gold Sage.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_86: boolean;

  /**
   * ### Master
   * Achieve the rank of Master.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_87: boolean;

  /**
   * ### Middle Master
   * Achieve the rank of Middle Master.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_88: boolean;

  /**
   * ### True Master
   * Achieve the rank of True Master.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_89: boolean;

  /**
   * ### Pole Weapon Mastery I
   * Reach Rank 10 with any three Scythe, Polearm or Staff weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_90: boolean;

  /**
   * ### Pole Weapon Mastery II
   * Reach Rank 20 with any three Scythe, Polearm or Staff weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_91: boolean;

  /**
   * ### Pole Weapon Mastery III
   * Reach Rank 30 with any three Scythe, Polearm or Staff weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_92: boolean;

  /**
   * ### Pole Weapon Proficiency I
   * Reach Rank 10 with any Scythe, Polearm or Staff weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_93: boolean;

  /**
   * ### Pole Weapon Proficiency II
   * Reach Rank 20 with any Scythe, Polearm or Staff weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_94: boolean;

  /**
   * ### Pole Weapon Proficiency III
   * Reach Rank 30 with any Scythe, Polearm or Staff weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_95: boolean;

  /**
   * ### All for One
   * Revive an ally.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_96: boolean;

  /**
   * ### Healer
   * Revive 10 allies.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_97: boolean;

  /**
   * ### Field Medic
   * Revive 100 allies.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_98: boolean;

  /**
   * ### Cheater of Death
   * Revive 1,000 allies.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_99: boolean;

  /**
   * ### Rifle Mastery I
   * Reach Rank 10 with any five Rifle or Machine Gun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_100: boolean;

  /**
   * ### Rifle Mastery II
   * Reach Rank 20 with any five Rifle or Machine Gun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_101: boolean;

  /**
   * ### Rifle Mastery III
   * Reach Rank 30 with any five Rifle or Machine Gun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_102: boolean;

  /**
   * ### Rifle Proficiency I
   * Reach Rank 10 with any Rifle or Machine Gun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_103: boolean;

  /**
   * ### Rifle Proficiency II
   * Reach Rank 20 with any Rifle or Machine Gun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_104: boolean;

  /**
   * ### Rifle Proficiency III
   * Reach Rank 30 with any Rifle or Machine Gun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_105: boolean;

  /**
   * ### Entrepreneur
   * Sell an item in the market.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_106: boolean;

  /**
   * ### Merchant
   * Sell 10,000 credits' worth of items.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_107: boolean;

  /**
   * ### Sentinel Mastery I
   * Reach Rank 10 with any three Sentinels.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_108: boolean;

  /**
   * ### Sentinel Mastery II
   * Reach Rank 20 with any three Sentinels.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_109: boolean;

  /**
   * ### Sentinel Mastery III
   * Reach Rank 30 with any three Sentinels.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_110: boolean;

  /**
   * ### Sentinel Proficiency I
   * Reach Rank 10 with any Sentinel.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_111: boolean;

  /**
   * ### Sentinel Proficiency II
   * Reach Rank 20 with any Sentinel.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_112: boolean;

  /**
   * ### Sentinel Proficiency III
   * Reach Rank 30 with any Sentinel.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_113: boolean;

  /**
   * ### Shotgun Mastery I
   * Reach Rank 10 with any two Shotgun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_114: boolean;

  /**
   * ### Shotgun Mastery II
   * Reach Rank 20 with any two Shotgun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_115: boolean;

  /**
   * ### Shotgun Mastery III
   * Reach Rank 30 with any two Shotgun weapons.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_116: boolean;

  /**
   * ### Shotgun Proficiency I
   * Reach Rank 10 with any Shotgun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_117: boolean;

  /**
   * ### Shotgun Proficiency II
   * Reach Rank 20 with any Shotgun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_118: boolean;

  /**
   * ### Shotgun Proficiency III
   * Reach Rank 30 with any Shotgun weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_119: boolean;

  /**
   * ### Shuriken Mastery I
   * Reach Rank 10 with any three Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_120: boolean;

  /**
   * ### Shuriken Mastery II
   * Reach Rank 20 with any three Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_121: boolean;

  /**
   * ### Shuriken Mastery III
   * Reach Rank 30 with any three Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_122: boolean;

  /**
   * ### Shuriken Proficiency I
   * Reach Rank 10 with any Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_123: boolean;

  /**
   * ### Shuriken Proficiency II
   * Reach Rank 20 with any Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_124: boolean;

  /**
   * ### Shuriken Proficiency III
   * Reach Rank 30 with any Boomerang, Throwing Discs or Throwing Daggers weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_125: boolean;

  /**
   * ### Agent
   * Solve a Cipher.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_126: boolean;

  /**
   * ### Special Agent
   * Solve 10 Ciphers.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_127: boolean;

  /**
   * ### Operative
   * Solve 100 Ciphers.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_128: boolean;

  /**
   * ### Cryptographer
   * Solve 1,000 Ciphers.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_129: boolean;

  /**
   * ### Counter Intelligence
   * Solve a Cipher in under 5 seconds.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_130: boolean;

  /**
   * ### No Longer a Rookie
   * Reach Rank 2 with any Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_131: boolean;

  /**
   * ### Practice Makes Perfect
   * Reach Rank 2 with any weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_132: boolean;

  /**
   * ### Alchemist
   * Complete 10 successful Mod Transmutes.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_133: boolean;

  /**
   * ### Combat Specialist
   * Complete 3 Sorties.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_134: boolean;

  /**
   * ### Control Freak
   * Complete an Interception node and extract with the enemy capturing 40% or less territory.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_135: boolean;

  /**
   * ### Dark Sectors
   * Complete 5 missions for a Clan that then wins a contested Dark Sector.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_136: boolean;

  /**
   * ### Egg Timer
   * Begin Genetic Lab Incubation for a Kubrow.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_137: boolean;

  /**
   * ### Hats off to you!
   * Destroy 200 Corpus Crewman helmets.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_138: boolean;

  /**
   * ### Hive Five!
   * Complete any 5 Hive Infestation missions.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_139: boolean;

  /**
   * ### Into the Void
   * Complete 10 Void Fissure missions.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_140: boolean;

  /**
   * ### KABOOM!
   * Kill 10 or more enemies with a single explosion (Tonkor, etc).
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_141: boolean;

  /**
   * ### Liberator
   * Set 10 hostages free without triggering the execution timer.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_142: boolean;

  /**
   * ### Mercenary
   * Earn Battle Pay from 5 Unique Invasions.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_143: boolean;

  /**
   * ### No Witnesses
   * Successfully perform 100 stealth kills.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_144: boolean;

  /**
   * ### Polarize This
   * Polarize a Weapon, Companion, or Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_145: boolean;

  /**
   * ### Polarize That
   * Reach Rank 30 with a polarized Weapon, Companion, or Warframe.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_146: boolean;

  /**
   * ### Ride the Wave
   * Complete 20 waves of Defense and successfully extract.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_147: boolean;

  /**
   * ### Saviour of Mercury
   * Kill the boss in the Mercury region and get to extraction.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_148: boolean;

  /**
   * ### Saviour of Venus
   * Kill the boss in the Venus region and get to extraction.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_149: boolean;

  /**
   * ### Saviour of Uranus
   * Kill the boss in the Uranus region and get to extraction.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_150: boolean;

  /**
   * ### Saviour of Sedna
   * Kill the boss in the Sedna region and get to extraction.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_151: boolean;

  /**
   * ### Shield Saver
   * Deflect 1,000 projectiles with your melee weapon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_152: boolean;

  /**
   * ### Tenno and Hooch
   * Complete any 10 missions with a Kubrow equipped.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_153: boolean;

  /**
   * ### Tenno of all Trades
   * Score a kill with your equipped primary, secondary and melee weapons in 5 seconds or less.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_154: boolean;

  /**
   * ### The 8-fold Path
   * Survive 8 waves of Defense using only melee attacks.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_155: boolean;

  /**
   * ### The Camera Adds 10 Pounds
   * Destroy 150 Security Cameras.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_156: boolean;

  /**
   * ### The Sword Alone
   * Complete 10 missions without any primary or secondary weapons equipped.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_157: boolean;

  /**
   * ### The War Within
   * Complete "The War Within" quest.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_158: boolean;

  /**
   * ### This is What You Are
   * Fully unlock a Focus skill tree.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_159: boolean;

  /**
   * ### What a Nightmare
   * Complete 10 Nightmare missions.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_160: boolean;

  /**
   * ### Without a Hitch
   * Complete a Hijack mission without allowing the payload to travel backwards.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_161: boolean;

  /**
   * ### From on High
   * Kill 100 grounded enemies while in Archwing Mode above the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_162: boolean;

  /**
   * ### Forged in Fire
   * Craft your first Zaw.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_163: boolean;

  /**
   * ### Champion of the People
   * Complete 10 bounties given by Ostron townspeople.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_164: boolean;

  /**
   * ### By the Dawn's Early Light
   * Survive a night on the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_165: boolean;

  /**
   * ### Marathoner
   * Travel 100,000 metres across the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_166: boolean;

  /**
   * ### Sleds of Sunshine
   * Travel over 500 metres in a single slide across the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_167: boolean;

  /**
   * ### Master Angler
   * Catch 10 fish.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_168: boolean;

  /**
   * ### Sharp Shooter
   * Kill an enemy from over 100 metres away across the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_169: boolean;

  /**
   * ### Pest Control
   * Kill 100 Plains Beasts.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_170: boolean;

  /**
   * ### Plains Prospector
   * Unearth 100 Deposits from the Plains of Eidolon.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_172: boolean;

  /**
   * ### Tomb Looter
   * Explore all of the Eidolon Caves.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_173: boolean;

  /**
   * ### The Great Eidolon Hunt
   * Defeat an Eidolon Teralyst.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_174: boolean;

  /**
   * ### Saya's Vigil
   * Complete "Saya's Vigil" quest.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_175: boolean;

  /**
   * ### The Sacrifice
   * Complete "The Sacrifice" quest.
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_176: boolean;

  /**
   * ### Joyride
   * Travel over 10,000 meters on a stolen Dargyn across the Plains of Eidolon
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_177: boolean;

  /**
   * ### Bounty Hunter
   * Complete 6 Bounties within 60 minutes while in Orb Vallis
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_178: boolean;

  /**
   * ### Airborne Exterminator
   * Destroy 10 Raknoids in Orb Vallis while airborn
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_179: boolean;

  /**
   * ### Ride or Die
   * Reach top standing with Ventkids
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_180: boolean;

  /**
   * ### Money Can't Buy Happiness
   * Reach top standing with Solaris United
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_181: boolean;

  /**
   * ### Moa Money, Moa Problems
   * Acquire a Moa pet
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_182: boolean;

  /**
   * ### K-Driven
   * Ride 1,000,000 meters on a K-Drive
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_183: boolean;

  /**
   * ### Hang Tenno
   * Make a 50 meter jump on a K-Drive
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_184: boolean;

  /**
   * ### Stay Frosty
   * Fall in coolant on Orb Vallis from 275 meters while on a K-Drive
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_185: boolean;

  /**
   * ### Vallis Spelunker
   * Explore all of the caves in Orb Vallis
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_186: boolean;

  /**
   * ### Race Ace
   * Complete all of the K-Drive races in Orb Vallis
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_187: boolean;

  /**
   * ### Animal Lover
   * Complete 10 perfect Conservation captures in Orb Vallis
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_188: boolean;

  /**
   * ### The Abyss Gazes Into You
   * Create a Kuva Lich
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_189: boolean;

  /**
   * ### That Which Does Not Kill Us
   * Kill a Kuva Lich commander
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_190: boolean;

  /**
   * ### Gonna Need a Bigger Boat
   * Enter the Dry Dock
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_191: boolean;

  /**
   * ### Some Assembly Required
   * Collect and assemble all Railjack components
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_192: boolean;

  /**
   * ### From out of the Sun
   * Shoot down 100 enemies while in a Railjack
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_193: boolean;

  /**
   * ### I'm the Captain Now
   * Pilot a hijacked enemy crewship during a Railjack mission
   * - default value: `false`
   * - hidden: `false`
   */
  ACHIEVEMENT_194: boolean;
}
