// This file is autogenerated by a script

export interface RocketLeagueAdapter {
  stats: RocketLeagueStats;
  achievements: RocketLeagueAchievements;
}

interface RocketLeagueStats {
  /**
   * ### __2
   * - default value: `0`
   */
  __2: number;

  /**
   * ### __3
   * - default value: `0`
   */
  __3: number;

  /**
   * ### __8
   * - default value: `0`
   */
  __8: number;

  /**
   * ### __11
   * - default value: `0`
   */
  __11: number;

  /**
   * ### __12
   * - default value: `0`
   */
  __12: number;

  /**
   * ### __18
   * - default value: `0`
   */
  __18: number;

  /**
   * ### __23
   * - default value: `0`
   */
  __23: number;

  /**
   * ### __40
   * - default value: `0`
   */
  __40: number;

  /**
   * ### __42
   * - default value: `0`
   */
  __42: number;

  /**
   * ### __51
   * - default value: `0`
   */
  __51: number;

  /**
   * ### __52
   * - default value: `0`
   */
  __52: number;

  /**
   * ### __53
   * - default value: `0`
   */
  __53: number;

  /**
   * ### __1
   * - default value: `0`
   */
  __1: number;

  /**
   * ### __69
   * - default value: `0`
   */
  __69: number;

  /**
   * ### __55
   * - default value: `0`
   */
  __55: number;

  /**
   * ### __74
   * - default value: `0`
   */
  __74: number;

  /**
   * ### __75
   * - default value: `0`
   */
  __75: number;

  /**
   * ### __81
   * - default value: `0`
   */
  __81: number;

  /**
   * ### __85
   * - default value: `0`
   */
  __85: number;
}

interface RocketLeagueAchievements {
  /**
   * ### Virtuoso
   * Unlock All Original Achievements
   * - default value: `false`
   * - hidden: `false`
   */
  Virtuoso: boolean;

  /**
   * ### Stocked
   * Collect 150 Items
   * - default value: `false`
   * - hidden: `false`
   */
  Stocked: boolean;

  /**
   * ### Far, Far Away...
   * Drive a total of 50 km
   * - default value: `false`
   * - hidden: `false`
   */
  FarFarAway: boolean;

  /**
   * ### Super Victorious
   * Win a total of 30 games across any game mode
   * - default value: `false`
   * - hidden: `false`
   */
  SuperVictorious: boolean;

  /**
   * ### Champion
   * Win the Season Championship
   * - default value: `false`
   * - hidden: `false`
   */
  Champion: boolean;

  /**
   * ### The Streak
   * Win 10 games in a row across any mode
   * - default value: `false`
   * - hidden: `false`
   */
  TheStreak: boolean;

  /**
   * ### Helen's Pride
   * Score 6 Goals in a single game
   * - default value: `false`
   * - hidden: `false`
   */
  HelensPride: boolean;

  /**
   * ### Car Collector
   * Collect 5 cars
   * - default value: `false`
   * - hidden: `false`
   */
  BattleCarCollector: boolean;

  /**
   * ### Drops in the Bucket
   * Collect 50 Items
   * - default value: `false`
   * - hidden: `false`
   */
  DropsintheBucket: boolean;

  /**
   * ### Rocketeer
   * Complete the regular Season
   * - default value: `false`
   * - hidden: `false`
   */
  Rocketeer: boolean;

  /**
   * ### Grease Monkey
   * Customize the Decal, Topper, Rocket Boost and Wheel on a car
   * - default value: `false`
   * - hidden: `false`
   */
  GreaseMonkey: boolean;

  /**
   * ### Pitch Veteran
   * Play a total of 20 games across any game mode
   * - default value: `false`
   * - hidden: `false`
   */
  PitchVeteran: boolean;

  /**
   * ### Rider's Block
   * Make 20 Saves
   * - default value: `false`
   * - hidden: `false`
   */
  RidersBlock: boolean;

  /**
   * ### Break Shot
   * Score a goal by hitting your opponent into the ball
   * - default value: `false`
   * - hidden: `false`
   */
  BreakShot: boolean;

  /**
   * ### Turbocharger
   * Use your Rocket Boost for a total of 5 minutes
   * - default value: `false`
   * - hidden: `false`
   */
  Turbocharger: boolean;

  /**
   * ### Drill Sergeant
   * Complete every Practice Drill (any difficulty)
   * - default value: `false`
   * - hidden: `false`
   */
  DrillSergeant: boolean;

  /**
   * ### Minute to Win it
   * With only 60 seconds left, Win a game in which you were tied or trailing
   * - default value: `false`
   * - hidden: `false`
   */
  MinutetoWinit: boolean;

  /**
   * ### Speed Demon
   * Completely fill and then empty your Rocket Boost 10 times in a single match
   * - default value: `false`
   * - hidden: `false`
   */
  SpeedDemon: boolean;

  /**
   * ### Pick-Me Up
   * Collect 5 Items
   * - default value: `false`
   * - hidden: `false`
   */
  PickMeUp: boolean;

  /**
   * ### Wall-Crawler
   * Drive on the dome walls for a total of 5 minutes
   * - default value: `false`
   * - hidden: `false`
   */
  WallCrawler: boolean;

  /**
   * ### Team Player
   * Play against every team in a Season
   * - default value: `false`
   * - hidden: `false`
   */
  TeamPlayer: boolean;

  /**
   * ### SARPBC Forever
   * Play one game each with Octane and Backfire
   * - default value: `false`
   * - hidden: `false`
   */
  SARPBCForever: boolean;

  /**
   * ### Feather in Your Recap
   * Watch a save file in Replay mode
   * - default value: `false`
   * - hidden: `false`
   */
  FeatherinYourRecap: boolean;

  /**
   * ### Winner
   * Win a total of 5 games across any mode
   * - default value: `false`
   * - hidden: `false`
   */
  Winner: boolean;

  /**
   * ### Clean Sheet
   * Win a game without giving up a single Goal
   * - default value: `false`
   * - hidden: `false`
   */
  CleanSheet: boolean;

  /**
   * ### Triple Threat
   * Win a 3v3 game
   * - default value: `false`
   * - hidden: `false`
   */
  TripleThreat: boolean;

  /**
   * ### Double Up
   * Win a 2v2 game
   * - default value: `false`
   * - hidden: `false`
   */
  DoubleUp: boolean;

  /**
   * ### Singles Club
   * Win a 1v1 game
   * - default value: `false`
   * - hidden: `false`
   */
  SinglesClub: boolean;

  /**
   * ### Perfect Start
   * Win your first game of the Season
   * - default value: `false`
   * - hidden: `false`
   */
  PerfectStart: boolean;

  /**
   * ### Still A Show-Off
   * Score a goal while reversing
   * - default value: `false`
   * - hidden: `false`
   */
  StillAShowOff: boolean;

  /**
   * ### Know the Drill
   * Complete a Practice Drill
   * - default value: `false`
   * - hidden: `false`
   */
  KnowTheDrill: boolean;

  /**
   * ### Traveler
   * Play a game in six different Arenas
   * - default value: `false`
   * - hidden: `false`
   */
  Traveler: boolean;

  /**
   * ### Tinkerer
   * Customize one slot on a car
   * - default value: `false`
   * - hidden: `false`
   */
  Tinkerer: boolean;

  /**
   * ### First-Timer
   * Score your first Goal
   * - default value: `false`
   * - hidden: `false`
   */
  FirstTimer: boolean;

  /**
   * ### Barras Bravas
   * Play an Online game with someone in your Party
   * - default value: `false`
   * - hidden: `false`
   */
  BarrasBravas: boolean;

  /**
   * ### Friendly
   * Play an Exhibition match
   * - default value: `false`
   * - hidden: `false`
   */
  Friendly: boolean;

  /**
   * ### Winning is Winning
   * Win a Season Championship using Dominus in every game
   * - default value: `false`
   * - hidden: `false`
   */
  WinningIsWinning: boolean;

  /**
   * ### An Inch and 6.2 Miles
   * Drive 10 km with the Vortex, Cristiano, or Spinner Wheels
   * - default value: `false`
   * - hidden: `false`
   */
  AnInchAnd62Miles: boolean;

  /**
   * ### Ride or Die
   * Equip Dominus or Takumi with any Decal, then win a game
   * - default value: `false`
   * - hidden: `false`
   */
  RideOrDie: boolean;

  /**
   * ### Don't Look Back
   * Use the Thermal, Burnout, or Nitrous Rocket Boost for a total of 10 minutes
   * - default value: `false`
   * - hidden: `false`
   */
  DontLookBack: boolean;

  /**
   * ### Family, Not Friends
   * Play a complete game with Dominus or Takumi
   * - default value: `false`
   * - hidden: `false`
   */
  FamilyNotFriends: boolean;

  /**
   * ### Drift King
   * Perform a 180 powerslide with Dominus or Takumi
   * - default value: `false`
   * - hidden: `false`
   */
  DriftKing: boolean;

  /**
   * ### Sky High
   * Score an Aerial Goal
   * - default value: `false`
   * - hidden: `false`
   */
  SkyHigh: boolean;

  /**
   * ### All Fours
   * Win a 4v4 game
   * - default value: `false`
   * - hidden: `false`
   */
  AllFours: boolean;

  /**
   * ### Gladiator
   * Play a game on Utopia Coliseum
   * - default value: `false`
   * - hidden: `false`
   */
  Gladiator: boolean;

  /**
   * ### Survival of the Fittest
   * Equip a Topper and win an Unfair Bot Match
   * - default value: `false`
   * - hidden: `false`
   */
  SurvivalOfTheFittest: boolean;

  /**
   * ### Heartbreaker
   * Win a game against All-Star Bots with a Decal equipped
   * - default value: `false`
   * - hidden: `false`
   */
  Heartbreaker: boolean;

  /**
   * ### Natural Progression
   * Win an Online Match with Backfire, Scarab, or Zippy
   * - default value: `false`
   * - hidden: `false`
   */
  NaturalProgression: boolean;

  /**
   * ### Throwback
   * Use the Standard or Accelerato Boost with Octane or Backfire while playing in Urban Central
   * - default value: `false`
   * - hidden: `false`
   */
  Throwback: boolean;

  /**
   * ### Hot Shot, Part Two
   * Win the MVP award using Backfire, Scarab, or Zippy
   * - default value: `false`
   * - hidden: `false`
   */
  HotShotPartTwo: boolean;

  /**
   * ### My World is Fire
   * Equip the Flamethrower Boost and win a 4v4 Online match
   * - default value: `false`
   * - hidden: `false`
   */
  MyWorldIsFire: boolean;

  /**
   * ### Spectacular
   * With Merc or Grog, Score 10 Goals against Pro-Level Bots or higher
   * - default value: `false`
   * - hidden: `false`
   */
  Spectacular: boolean;

  /**
   * ### Savage
   * With Ripper, Score 10 Goals against Pro-level Bots or higher
   * - default value: `false`
   * - hidden: `false`
   */
  Savage: boolean;

  /**
   * ### Ruthless
   * Make 50 total Shots on Goal using Merc, Grog, or Ripper
   * - default value: `false`
   * - hidden: `false`
   */
  Ruthless: boolean;

  /**
   * ### Psycho-Master Exploder
   * Demolish 3 opposing bots in Wasteland
   * - default value: `false`
   * - hidden: `false`
   */
  PsychoMasterExploder: boolean;

  /**
   * ### Mad Scientist
   * Play a complete match in 3 different Rocket Labs Arenas
   * - default value: `false`
   * - hidden: `false`
   */
  MadScientist: boolean;

  /**
   * ### Icing the Cake
   * In Snow Day, score a goal from your own side of the ice
   * - default value: `false`
   * - hidden: `false`
   */
  IcingTheCake: boolean;

  /**
   * ### Left Wing, Right Wing
   * Win a Snow Day match with both the Blue and Orange teams
   * - default value: `false`
   * - hidden: `false`
   */
  LeftWingRightWing: boolean;

  /**
   * ### Fast Break
   * Score at least 2 Dunks in the first minute of a Hoops game
   * - default value: `false`
   * - hidden: `false`
   */
  FastBreak: boolean;

  /**
   * ### Buzzer Beater
   * With 30 seconds left, win a game of Hoops in which you were tied or trailing
   * - default value: `false`
   * - hidden: `false`
   */
  BuzzerBeater: boolean;

  /**
   * ### Budding Artist
   * Collect a Painted Item
   * - default value: `false`
   * - hidden: `false`
   */
  BuddingArtist: boolean;

  /**
   * ### One Better
   * Increase the level of a Certified Item
   * - default value: `false`
   * - hidden: `false`
   */
  OneBetter: boolean;

  /**
   * ### Certifiable
   * Earn Veteran status for your Certified Item
   * - default value: `false`
   * - hidden: `false`
   */
  Certifiable: boolean;

  /**
   * ### GG
   * Win the MVP award in a game that goes to overtime
   * - default value: `false`
   * - hidden: `false`
   */
  GG: boolean;

  /**
   * ### Trifecta
   * Score a Goal, Save a shot, and Assist a teammate in a single game
   * - default value: `false`
   * - hidden: `false`
   */
  Trifecta: boolean;

  /**
   * ### Infinite Power!
   * Activate every power-up in Rumble mode
   * - default value: `false`
   * - hidden: `false`
   */
  InfinitePower: boolean;

  /**
   * ### Stopped Cold
   * In Rumble, freeze an opponent's shot before it can score
   * - default value: `false`
   * - hidden: `false`
   */
  StoppedCold: boolean;

  /**
   * ### Sea Turtle
   * Head to AquaDome and score a goal while flipped on your back
   * - default value: `false`
   * - hidden: `false`
   */
  SeaTurtle: boolean;

  /**
   * ### Get Up, Mr. Bubbles!
   * Score an Aerial goal while playing in AquaDome
   * - default value: `false`
   * - hidden: `false`
   */
  GetUpMrBubbles: boolean;

  /**
   * ### Rocket Repleter
   * Make 535 Shots on Goal
   * - default value: `false`
   * - hidden: `false`
   */
  RocketGenocider: boolean;

  /**
   * ### Registered Voter
   * Head to 'Arena Preferences' and use all of your votes
   * - default value: `false`
   * - hidden: `false`
   */
  RegisteredVoter: boolean;

  /**
   * ### Metaverse
   * Equip the Ion Rocket Boost or the Halo Topper and win a match on Starbase ARC
   * - default value: `false`
   * - hidden: `false`
   */
  Metaverse: boolean;

  /**
   * ### Brave the Elements
   * Complete a match on wasted land, under the sea, and in outer space
   * - default value: `false`
   * - hidden: `false`
   */
  BraveTheElements: boolean;

  /**
   * ### Damage Control
   * Win a Dropshot match via shutout
   * - default value: `false`
   * - hidden: `false`
   */
  DamageControl: boolean;

  /**
   * ### Full Course
   * Score a total of 18 Goals in Dropshot
   * - default value: `false`
   * - hidden: `false`
   */
  FullCourse: boolean;

  /**
   * ### Buckminster x10
   * Damage a total of 320 panels in Dropshot
   * - default value: `false`
   * - hidden: `false`
   */
  BuckministerX10: boolean;

  /**
   * ### Storm Trooper
   * Equip a Very Rare Item and complete a game in an Arena with turbulent weather
   * - default value: `false`
   * - hidden: `false`
   */
  StormTrooper: boolean;

  /**
   * ### Good Times
   * Head to Champions Field and complete an Online game
   * - default value: `false`
   * - hidden: `false`
   */
  GoodTimes: boolean;

  /**
   * ### Swap Meet
   * Trade and receive one or more items with another player in a single transaction
   * - default value: `false`
   * - hidden: `false`
   */
  SwapMeet: boolean;

  /**
   * ### Trade Secret
   * Trade In five items of the same quality to receive an item of the next-highest quality
   * - default value: `false`
   * - hidden: `false`
   */
  TradeSecret: boolean;

  /**
   * ### Rank Up
   * Complete all placement matches in any Competitive Playlist
   * - default value: `false`
   * - hidden: `false`
   */
  RankUp: boolean;

  /**
   * ### Coming On Strong
   * Score or Assist a combined 30 goals or assists in Casual or Competitive Online matches
   * - default value: `false`
   * - hidden: `false`
   */
  ComingOnStrong: boolean;

  /**
   * ### Join the Club!
   * Create or Join a Rocket League Club
   * - default value: `false`
   * - hidden: `false`
   */
  JointheClub: boolean;

  /**
   * ### Together is Better
   * Play and complete an Online match with one or more Clubmates
   * - default value: `false`
   * - hidden: `false`
   */
  TogetherisBetter: boolean;

  /**
   * ### New Challenger
   * Join and complete an Online Tournament match
   * - default value: `false`
   * - hidden: `false`
   */
  NewChallenger: boolean;

  /**
   * ### People Person
   * Play and complete 10 Online matches with one or more Clubmates
   * - default value: `false`
   * - hidden: `false`
   */
  PeoplePerson: boolean;

  /**
   * ### Squad Goals
   * Score a Goal while in a Club Match (Online Matchmaking only)
   * - default value: `false`
   * - hidden: `false`
   */
  SquadGoals: boolean;

  /**
   * ### Best of the Bunch
   * Earn the MVP award in any Online Tournament match
   * - default value: `false`
   * - hidden: `false`
   */
  BestoftheBunch: boolean;
}
